### ISSUE TITLE
Low GPU Usage with DALI

### ISSUE THREAD

**Issue by bensuucar** [NVIDIA/DALI#2138] opened 2020-07-21 17:59 UTC
The GPU usage is only %2-3 during training. It makes me question if I have a bottleneck process while preparing the data with DALI. I need to define a random integer value in my **ExternalInputIterator** and I define it with **offset = np.random.randint(low = -20, high= 16)** because I couldn't find any operator in DALI to generate random INT values. Do you think it might be causing the issue?

Besides, I am getting the following error:

 RuntimeWarning: Method (on_train_batch_end) is slow compared to the batch update (0.364041). Check your callbacks. % (hook_name, delta_t_median), RuntimeWarning)

I know that this does not necessarily come from DALI but it might be coming from my Generator class which I wrote to create train and validation generators to use with **fit_generator** in keras.

Could you please point out if you spot any problem with the code below. Thank you!

``` 
class GeneratorDali:
    def __init__(self,image_dir, mode, batch_size, gpu_ids):
        self.n = 0
        if (mode=='train'):
            self.pipe= TrainPipeline(image_dir,
            batch_size,
            num_threads = 2, 
            device_id = gpu_ids[0] ,
            mode='train')
            self.epochsize= (int(np.ceil(len(os.listdir(os.path.join(image_dir,mode)))/batch_size)))

        elif mode =='val':
            self.pipe = ValPipeline(image_dir,
            batch_size,
            num_threads = 2,
            device_id = gpu_ids[0],  
            mode='val')
            self.epochsize= (int(np.ceil(len(os.listdir(os.path.join(image_dir,mode)))/batch_size)))

        self.pipe.build()

    def __iter__(self):
        return self
    def __next__(self):
        return self.next()     
    def next(self):
        self.n+=1
        self.pipe_out = self.pipe.run()
        if self.n== self.epochsize:
            self.pipe.reset()
            self.n=0   
 
        return (self.pipe_out[0].as_cpu().as_array()/255.0 , self.pipe_out[1].as_array())

```

**Comment by JanuszL** [comment] 2020-07-21 18:23
Hi,
First of all, ExternalSource doesn't scale with the number of CPU cores available, it is most flexible but inferior to the other Readers.
If you want to generate a numer in the given range I think you can use [Uniform operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Uniform), multiply the returned value by the range and subtract the minimal value using [build-in arithmetic DALI operations](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/index.html) and then use [cast operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Cast) to convert from float to int:
```
def define_graph(self):
   out = self.unform_op()
   out = out * 36 - 20
   out = self.cast_op(out)
```
Also I see that you are doing the round trip GPU->CPU->GPU by calling `.as_cpu().as_array()`. This is not recommended.
According to [TF docs](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit_generator) `fit_generator` is deprecated, please use `Model.fit` You can see how to use DALI with `Model.fit` in [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/tensorflow/tensorflow-dataset.html#Keras).

**Comment by bensuucar** [comment] 2020-07-21 20:25
Thank you for the answer.

I tried to implement Model.fit like you pointed out in the example.

To be able to use **dali_tf.DALIDataset**, I need to have **import nvidia.dali.plugin.tf as dali_tf**

However I have the following error:

Bad key "text.kerning_factor" on line 4 in
/home/bensu/anaconda3/envs/efficientDet/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
Traceback (most recent call last):
  File "train_dali.py", line 18, in <module>
    import nvidia.dali.plugin.tf as dali_tf
  File "/home/bensu/anaconda3/envs/efficientDet/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 24, in <module>
    _dali_tf_module = dali_tf_plugin.load_dali_tf_plugin()
  File "/home/bensu/anaconda3/envs/efficientDet/lib/python3.7/site-packages/nvidia/dali_tf_plugin/dali_tf_plugin.py", line 47, in load_dali_tf_plugin
    raise first_error or Exception('No matching DALI plugin found for installed TensorFlow version')
  File "/home/bensu/anaconda3/envs/efficientDet/lib/python3.7/site-packages/nvidia/dali_tf_plugin/dali_tf_plugin.py", line 40, in load_dali_tf_plugin
    _dali_tf_module = tf.load_op_library(libdali_tf)
  File "/home/bensu/anaconda3/envs/efficientDet/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/bensu/anaconda3/envs/efficientDet/lib/python3.7/site-packages/nvidia/dali/libdali.so: version `DALI_0.23.0' not found (required by /home/bensu/anaconda3/envs/efficientDet/lib/python3.7/site-packages/nvidia/dali_tf_plugin/libdali_tf_1_15.so)



I installed DALI and TF plugin with the instructions recommended on the website.

pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda100
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-tf-plugin-cuda100

and I have tensorflow-gpu 1.15

I believe this installation is causing the error and it cannot find nvidia.dali.plugin.tf. 

I tried older versions of tensorflow , dali and dali tf plugin combination, however it didnt work either.

Maybe you have seen this error before? Thank you

**Comment by JanuszL** [comment] 2020-07-21 20:32
Hi,

Just to be sure please remove all DALI installations you have so far and then do a clean install:
```
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda100
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-tf-plugin-cuda100
```
It looks like there are some leftovers from the older DALI version.

**Comment by bensuucar** [comment] 2020-07-22 09:01
I installed tensorflow-gpu 1.15 , DALI and DALI tf plugin on a new environment not to have leftovers as you mentioned. However it didn't succeed. I tired different tensorflow versions and DALI nightly but I am getting the following error unfortunately:

Using TensorFlow backend.
Traceback (most recent call last):
  File "train_dali.py", line 18, in <module>
    import nvidia.dali.plugin.tf as dali_tf
  File "/home/bensu/anaconda3/envs/dalikerf/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 24, in <module>
    _dali_tf_module = dali_tf_plugin.load_dali_tf_plugin()
  File "/home/bensu/anaconda3/envs/dalikerf/lib/python3.7/site-packages/nvidia/dali_tf_plugin/dali_tf_plugin.py", line 47, in load_dali_tf_plugin
    raise first_error or Exception('No matching DALI plugin found for installed TensorFlow version')
  File "/home/bensu/anaconda3/envs/dalikerf/lib/python3.7/site-packages/nvidia/dali_tf_plugin/dali_tf_plugin.py", line 40, in load_dali_tf_plugin
    _dali_tf_module = tf.load_op_library(libdali_tf)
  File "/home/bensu/anaconda3/envs/dalikerf/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/bensu/anaconda3/envs/dalikerf/lib/python3.7/site-packages/nvidia/dali_tf_plugin/libdali_tf_1_15.so: undefined symbol: _ZN10tensorflow14DataTypeStringENS_8DataTypeE


There is a related issue [here](https://github.com/NVIDIA/DALI/issues/1200) and there it is stated that T**here are some binary compatibility problems when you mix a tensorflow-gpu and DALI tensorflow plugin build with different compilers.** 
But it is not clear what the solution approach should be since DALI Nightly didnt work. And maybe there is an improvement since then?

**Comment by JanuszL** [comment] 2020-07-22 13:47
Hi,

I have missed the fact that you are using a community TensorFlow build. DALI provides the pre-build plugin only for upstream, Google build TensorFlow as this is the one they recommend - https://www.tensorflow.org/install/pip#conda.
If you really must you can set `export DALI_TF_ALWAYS_BUILD=1` before installing `nvidia-dali-tf-plugin-cuda100` package to rebuild plugin for your TF installation. The prerequisites are to have a proper gcc compiler and CUDA available.

**Comment by bensuucar** [comment] 2020-07-22 14:24
Thank you for the response. 

I tired your suggestion, it still fails at **import nvidia.dali.plugin.tf as dali_tf**
I am still getting the error in the previous commend.

Thus, I am not able to use model.fit. For this reason I would like to post my recent code with fit_generator, so maybe you can help me to spot the inefficiency causing the **low memory and low GPU utilization**. 

```
import os
import glob
import types
import cv2
import collections
import numpy as np
from random import shuffle
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.fn as fn
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt


def show_images(image_batch):
    columns = 2
    rows = (batch_size + 1) // (columns)
    fig = plt.figure(figsize = (32,(32 // columns) * rows))
    gs = gridspec.GridSpec(rows, columns)
    for j in range(rows*columns):
        plt.subplot(gs[j])
        plt.axis("off")
        plt.imshow(image_batch.at(j))

class ExternalInputIterator(object):
    def __init__(self,image_dir, batch_size, device_id, mode):

        self.mode = mode
        self.images_dir = image_dir
        self.batch_size = batch_size
        self.device_id = device_id

        with open(self.images_dir +'/' + self.mode + ".txt", 'r') as f:
            self.files = [line.rstrip() for line in f if line is not '']
        shuffle(self.files)

    def __iter__(self):
        self.i = 0
        self.n = len(self.files)
        return self


    def __next__(self):
        batch = []
        labels = []
        crop_anchor = []
        crop_shape = []
        

        if self.i >= self.n:
            raise StopIteration

        for _ in range(self.batch_size):
            jpeg_filename, label = self.files[self.i].split(' ')
            
            f = open(self.images_dir + '/' + self.mode + '/' + jpeg_filename, 'rb')
            batch.append(np.frombuffer(f.read(), dtype = np.uint8))
            if 'Left' in jpeg_filename:
                offset = np.random.randint(low = -20, high= 16)
                offset_x = np.random.randint(low = 0, high= 500)
                crop_y = 591 + offset                                                        
                crop_x = 20 + offset_x                                                
                labels.append(np.array([float(label) + offset ], dtype = np.float32))  #offset

            elif 'Right' in jpeg_filename:
                offset = np.random.randint(low = -20, high= 16)
                offset_x = np.random.randint(low = 0, high= 500)
                crop_y = 591 + offset                                                  
                crop_x = 1550 - offset_x                                                    
                labels.append(np.array([float(label) + offset ], dtype = np.float32))  #offset
                
            elif 'Bottom' in jpeg_filename:
                offset = np.random.randint(low = -12, high= 3) 
                offset_y = np.random.randint(low = 0, high= 400)
                crop_y = 1162 - offset_y                                                
                crop_x = 786 + offset                                                  
                labels.append(np.array([float(label) - offset ], dtype = np.float32))  #offset
                
            else:
                offset = np.random.randint(low = -12, high= 3)  
                offset_y = np.random.randint(low = 0, high= 400) 
                crop_y = 20 +  offset_y                                                 
                crop_x = 786 + offset                                                           
                labels.append(np.array([float(label) - offset ], dtype = np.float32))  #offset
                
            crop_shape.append(np.array([52,52], dtype=np.float32))
            crop_anchor.append(np.array([crop_x, crop_y] , dtype = np.float32))
            self.i = (self.i + 1) % self.n
        return (batch, labels, crop_anchor, crop_shape)

    #@property
    #def size(self,):
    #    return self.data_set_len

    next = __next__

class TrainPipeline(Pipeline):
    def __init__(self,image_dir,batch_size,num_threads, device_id, mode='train'):
        super(TrainPipeline,self).__init__(batch_size,num_threads,device_id, seed=12)
        eii = ExternalInputIterator(image_dir,batch_size,device_id, mode = 'train')
        self.iterator = iter(eii)
        self.decoder_slice = ops.ImageDecoderSlice(device = 'mixed', normalized_anchor = False, normalized_shape = False, axis_names = "WH",  output_type=types.GRAY)
        #self.slice = ops.Slice(device = 'gpu', normalized_anchor = False, normalized_shape = False, axis_names = "WH", out_of_bounds_policy='pad')
        self.brightness=ops.NormalDistribution(mean=1.0, stddev=0.3)
        self.contrast=ops.NormalDistribution(mean=1.0, stddev=0.3) 
        self.BC= ops.BrightnessContrast(device = "gpu")

    def define_graph(self):
        self.jpegs       = fn.external_source(device = 'cpu', name = "jpegs")
        self.labels      = fn.external_source(device = 'cpu', name = "labels")
        self.crop_anchor = fn.external_source(device = 'cpu', name = "crop_anchor")
        self.crop_shape  = fn.external_source(device = 'cpu', name = "crop_shape")
        images = self.decoder_slice(self.jpegs, self.crop_anchor, self.crop_shape)
        output = self.BC(images,brightness=self.brightness(),contrast=self.contrast())
        return output, self.labels

    def iter_setup(self):
        (images, labels, crop_anchor, crop_shape) = self.iterator.next()
        self.feed_input("jpegs", images)
        self.feed_input("labels", labels)
        self.feed_input("crop_anchor", crop_anchor)
        self.feed_input("crop_shape", crop_shape)
        
class ValPipeline(Pipeline):
    def __init__(self,image_dir,batch_size, num_threads, device_id, mode='val'):
        super(ValPipeline,self).__init__(batch_size,num_threads,device_id, seed=12)
        eii = ExternalInputIterator(image_dir,batch_size,device_id, mode = 'val')
        self.iterator = iter(eii)
        self.decoder_slice = ops.ImageDecoderSlice(device = 'mixed', normalized_anchor = False, normalized_shape = False, axis_names = "WH" ,  output_type=types.GRAY)

    def define_graph(self):
        self.jpegs       = fn.external_source(device = 'cpu', name = "jpegs")
        self.labels      = fn.external_source(device = 'cpu', name = "labels")
        self.crop_anchor = fn.external_source(device = 'cpu', name = "crop_anchor")
        self.crop_shape  = fn.external_source(device = 'cpu', name = "crop_shape")
        output = self.decoder_slice(self.jpegs, self.crop_anchor, self.crop_shape)
        return output, self.labels

    def iter_setup(self):
        (images, labels, crop_anchor, crop_shape) = self.iterator.next()
        self.feed_input("jpegs", images)
        self.feed_input("labels", labels)
        self.feed_input("crop_anchor", crop_anchor)
        self.feed_input("crop_shape", crop_shape)


class GeneratorDali:
    def __init__(self,image_dir, mode, batch_size, device_id ):
        self.n = 0
        if (mode=='train'):
            self.pipe= TrainPipeline(image_dir,
            batch_size,
            num_threads = 2, 
            device_id =0 ,
            mode='train')
            self.epochsize= (int(np.ceil(len(os.listdir(os.path.join(image_dir,mode)))/batch_size)))

        elif mode =='val':
            self.pipe = ValPipeline(image_dir,
            batch_size,
            num_threads = 2,
            device_id = 0,  
            mode='val')
            self.epochsize= (int(np.ceil(len(os.listdir(os.path.join(image_dir,mode)))/batch_size)))

        self.pipe.build()

    def __iter__(self):
        return self
    def __next__(self):
        return self.next()     
    def next(self):
        self.n+=1
        self.pipe_out = self.pipe.run()
        if self.n== self.epochsize:
            self.pipe.reset()
            self.n=0   
            debug=0

        for x in range(self.pipe_out[0].as_cpu().as_array().shape[0]):
            cv2.imwrite("/home/bensu/Desktop/Share/Models/KerfImages/data_dali/debug/"+'Img_{}.png'.format(str(x)),self.pipe_out[0].as_cpu().as_array().take(x,axis=0))
        

        return (self.pipe_out[0].as_cpu().as_array() , self.pipe_out[1].as_array())

```

Then here I use train_generator

```
network = create_deep_learning_network(input_shape, conv_layers_dimensions, dense_layers_dimensions)
checkpoint = ModelCheckpoint( path + '/' + 'model{epoch:08d}.h5', period=50) 

tensorboard = keras.callbacks.TensorBoard(log_dir="/home/bensu/Desktop/Share/Models/KerfImages/logs/fit/{}".format(model_name))

### Print deep learning network summary
print(network.summary())

train_generator = GeneratorDali(image_dir= image_dir , mode = 'train', batch_size= batch_size, device_id  = device_id )
val_generator = GeneratorDali(image_dir= image_dir , mode = 'val', batch_size=batch_size , device_id  =device_id )

    
train_generator_length = (int(np.ceil(len(os.listdir(os.path.join(image_dir,'train')))/batch_size)))
val_generator_length = (int(np.ceil(len(os.listdir(os.path.join(image_dir,'val')))/batch_size)))


network.fit_generator(train_generator, validation_data=val_generator, epochs=400, steps_per_epoch= train_generator_length , validation_steps= val_generator_length,  verbose=1, use_multiprocessing=False, workers=1, callbacks=[tensorboard,checkpoint])
network.save(path + '.h5')   


```

I do not know why I cannot utilize the memory and gpu. I appreciate your help!

**Comment by JanuszL** [comment] 2020-07-22 17:30
Hi,
Have you tried to install TensorFlow from pip - I checked and this works fine for me.
Regarding your pipeline you should not use ExternalSource - it is inferior regarding perf compared to other Readers.
Also when you do `.as_cpu().as_array()` you transferring data from GPU to CPU, then TF is moving it back to GPU. SO this round trip is definitely a thing you want to avoid, and the tutorial with the DALI dataset shows how to avoid it.

**Comment by bensuucar** [comment] 2020-07-22 21:09
Yes, I tried however it didn't succeed, is it possible to specify which command you tried for tensorflow and DALI? Because it exactly says that there is no matching tensorflow distribution found. 
I am using ExternalSource because I need to load my continuous labels from a csv or txt file, so I cannot extract them from a folder structure. That is why I couldn't use other Readers in Dali. 
Thank you!

**Comment by JanuszL** [comment] 2020-07-23 11:01
What I did is:
```
conda create -n python3.7 python=3.7 -y
conda activate python3.7
pip install tensorflow-gpu==1.15
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda100
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-tf-plugin-cuda100
python -c "import nvidia.dali.plugin.tf as dali_tf"
```
Following line would slow you down significantly as well:
```
for x in range(self.pipe_out[0].as_cpu().as_array().shape[0]):
            cv2.imwrite("/home/bensu/Desktop/Share/Models/KerfImages/data_dali/debug/"+'Img_{}.png'.format(str(x)),self.pipe_out[0].as_cpu().as_array().take(x,axis=0))
```
If you need to use ExternalInputIterator then you cannot use the DALI dataset, and you would suffer this round trip GPU->CPU->GPU.

**Comment by bensuucar** [comment] 2020-07-23 14:01
I managed to successfully install and import everything. For the following code, I am getting the corresponding error. 

```
trainpipeline = TrainPipeline(image_dir, batch_size, device='gpu', num_threads=2, device_id=gpu_ids[0] , mode='train')


shapes = ((batch_size, 52, 52),(batch_size))
dtypes = (tf.float32,tf.float32)

ITERATIONS_PER_EPOCH = (int(np.ceil(len(os.listdir(os.path.join(image_dir,'train')))/batch_size)))

with tf.device('/gpu:0'):
    train_set = dali_tf.DALIDataset(pipeline=trainpipeline, batch_size=batch_size, output_shapes=shapes, output_dtypes=dtypes, device_id=gpu_ids[0])
    print(train_set)
    network.fit( train_set, epochs=400 , steps_per_epoch=ITERATIONS_PER_EPOCH)

network.save(path + '.h5')   

```

Error:

<DALIDataset shapes: ((128, 52, 52), (128,)), types: (tf.float32, tf.float32)>
Traceback (most recent call last):
  File "train_dali.py", line 155, in <module>
    network.fit( train_set, epochs=400 , steps_per_epoch=ITERATIONS_PER_EPOCH)
  File "/usr/lib/python3/dist-packages/keras/engine/training.py", line 952, in fit
    batch_size=batch_size)
  File "/usr/lib/python3/dist-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/usr/lib/python3/dist-packages/keras/engine/training_utils.py", line 92, in standardize_input_data
    data = [standardize_single_array(x) for x in data]
  File "/usr/lib/python3/dist-packages/keras/engine/training_utils.py", line 92, in <listcomp>
    data = [standardize_single_array(x) for x in data]
  File "/usr/lib/python3/dist-packages/keras/engine/training_utils.py", line 27, in standardize_single_array
    elif x.ndim == 1:
AttributeError: 'DALIDataset' object has no attribute 'ndim'



As you said, I believe it is related to the fact that I am using ExternalSource, so I cannot use DALI dataset. 
So for my specific situation with continuous labels from a csv or txt file, there is no Reader available in DALI that I can use DALI dataset. Is that true? 
Then the only way to convert the images and labels to arrays to fit to keras is doing this GPU->CPU->GPU.  And apparently it is lowering the performance so I cannot gain to much from augmenting on GPU. 

Furthermore, in [the example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/tensorflow/tensorflow-dataset.html#Keras) you reference before, it says the following:

**In this particular toy example performance of the GPU variant is lower than the CPU one. The MNIST images are small and nvJPEG decoder used in the GPU DALI pipeline to decode them is not well suited for such circumstance. We use it here to show how to integrate it properly in the real life case.**

In my case I am cropping 52x52 patches from images with resolution 1624x1234. So this might be thing mentioned above? But it still does not explain why it affect gpu usage during training.

**Comment by JanuszL** [comment] 2020-07-23 14:27
Hi,
```
In this particular toy example performance of the GPU variant is lower than the CPU one. The MNIST images are small and nvJPEG decoder used in the GPU DALI pipeline to decode them is not well suited for such circumstance. We use it here to show how to integrate it properly in the real life case.
```
Is about input images. If your input is `1624x1234` then you are good. You can also try to run the pipeline only on the CPU and see if there is any speed difference.
I will check
```
elif x.ndim == 1:
AttributeError: 'DALIDataset' object has no attribute 'ndim'
```
and get back to you.

**Comment by awolant** [comment] 2020-07-23 17:39
Hi,
I looked into the `AttributeError: 'DALIDataset' object has no attribute 'ndim'` issue and unfortunately I was not able to reproduce it myself. In my setup with TF 1.15 similar scenario works as expected. Additionally, I looked through the TF code and was not able to find the offending line in there.
Are you using `tensorflow.keras` or just `keras`? DALI is tested with the former one and there is a known issue in the latter that looks similar to this. Please, try using `tensorflow.keras` and let's see, if it helps.
If it won't work, please provide a full reproduction for us to run.

**Comment by bensuucar** [comment] 2020-07-30 13:49
Hi,
Thanks for the answer.
Using tensorflow.keras helped to eliminated the error. 
However this time, the training does not start and it does not give any error either. It just does not progress from this point:

2020-07-30 13:42:13.949324: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-07-30 13:42:13.949413: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-07-30 13:42:13.949487: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-07-30 13:42:13.949558: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-07-30 13:42:13.949631: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-07-30 13:42:13.949703: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-07-30 13:42:13.949776: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-30 13:42:13.956543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-07-30 13:42:13.956617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-30 13:42:13.956638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-07-30 13:42:13.956654: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-07-30 13:42:13.964524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7634 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:88:00.0, compute capability: 7.5)
Train on 23000 steps
Epoch 1/400
2020-07-30 13:42:17.009106: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0

**Comment by awolant** [comment] 2020-07-30 22:04
Great, we are one step further. Could you enable more logs from TensorFlow and share the result. This looks fine. 
If you could provide some kind of self contained reproduction, that would be best.

**Comment by Mert-Ergin** [comment] 2020-10-07 19:30
This is not related to DALI. It is related to Keras version you are using. Keras does not support fit_generator in fit before keras version 2.2.5. If you update to 2.2.5 you will not have this issue. You can also try 2.2.4 and fit_generator instead of fit.

**Comment by Mert-Ergin** [comment] 2020-10-07 19:49
This is not relate to DALI. It is related to keras. You are passing a generator to model.fit. This is not supported for earlier versions of Keras.

**Closed** 2021-04-14 16:45 UTC
Labels: question
