### ISSUE TITLE
How to load ImageNet22k data by DALI? 

### ISSUE THREAD

**Issue by Ema1997** [NVIDIA/DALI#2798] opened 2021-03-16 13:30 UTC
Hi,
I tried to load ImageNet22k data using DALI, but I have encountered errors. The error messages are as follows:
![image](https://user-images.githubusercontent.com/19912756/111316055-e54dca00-869d-11eb-9dc0-4ac6a6ce3935.png)
When loading ImageNet1k data, this code works fine. Therefore, would you please tell me how to modify the data loader code?
My origin code:
```python
class HybridTrainPipe(Pipeline):
	def __init__(self, batch_size, num_threads, device_id, data_dir, crop, dali_cpu=False, args=None):
		super(HybridTrainPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
		self.input = ops.FileReader(file_root=data_dir, shard_id=args.local_rank, num_shards=args.world_size, random_shuffle=True)
		#let user decide which pipeline works him bets for RN version he runs
		dali_device = 'cpu' if dali_cpu else 'gpu'
		decoder_device = 'cpu' if dali_cpu else 'mixed'
		# This padding sets the size of the internal nvJPEG buffers to be able to handle all images from full-sized ImageNet
		# without additional reallocations
		device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
		host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
		# The cropping window’s area (relative to the entire image) and aspect ratio can be restricted to
		# a range of values specified by area and aspect_ratio arguments, respectively.
		self.decode = ops.ImageDecoderRandomCrop(device=decoder_device, output_type=types.RGB,
		                                         device_memory_padding=device_memory_padding,
		                                         host_memory_padding=host_memory_padding,
		                                         random_aspect_ratio=[0.8, 1.25],
		                                         random_area=[0.1, 1.0],
		                                         num_attempts=100,
		                                         memory_stats=True)
		self.res = ops.Resize(device=dali_device, resize_x=crop, resize_y=crop, interp_type=types.INTERP_TRIANGULAR)
		self.cmnp = ops.CropMirrorNormalize(device="gpu",
		                                    dtype=types.FLOAT,
		                                    output_layout=types.NCHW,
		                                    crop=(crop, crop),
		                                    image_type=types.RGB,
		                                    mean=[0.485 * 255,0.456 * 255,0.406 * 255],
		                                    std=[0.229 * 255,0.224 * 255,0.225 * 255])
		self.coin = ops.CoinFlip(probability=0.5)
		logging.info('DALI "{0}" variant'.format(dali_device))

	def define_graph(self):
		rng = self.coin()
		self.jpegs, self.labels = self.input(name="Reader")
		images = self.decode(self.jpegs)
		images = self.res(images)
		output = self.cmnp(images.gpu(), mirror=rng)
		return [output, self.labels]


class HybridValPipe(Pipeline):
	def __init__(self, batch_size, num_threads, device_id, data_dir, crop, size, args=None):
		super(HybridValPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
		self.input = ops.FileReader(file_root=data_dir, shard_id=args.local_rank, num_shards=args.world_size, random_shuffle=False)
		self.decode = ops.ImageDecoder(device="mixed", output_type=types.RGB)
		self.res = ops.Resize(device="gpu", resize_shorter=size, interp_type=types.INTERP_TRIANGULAR)
		self.cmnp = ops.CropMirrorNormalize(device="gpu",
		                                    dtype=types.FLOAT,
		                                    output_layout=types.NCHW,
		                                    crop=(crop, crop),
		                                    image_type=types.RGB,
		                                    mean=[0.485 * 255,0.456 * 255,0.406 * 255],
		                                    std=[0.229 * 255,0.224 * 255,0.225 * 255])

	def define_graph(self):
		self.jpegs, self.labels = self.input(name="Reader")
		images = self.decode(self.jpegs)
		images = self.res(images)
		output = self.cmnp(images)
		return [output, self.labels]


def getDatasetDali(args, data_dir):
	crop_size = 224
	val_size = 256
	if args.ImageNet22k:
		train_dir = os.path.join(data_dir, "ImageNet22k")
		val_dir = os.path.join(data_dir, "val")

	else:
		train_dir = os.path.join(data_dir, "train")
		val_dir = os.path.join(data_dir, "val")
		# train_dir = os.path.join(data_dir, "train_small")
		# val_dir = os.path.join(data_dir, "val_small")
	pipe = HybridTrainPipe(batch_size=args.batch_size, num_threads=args.workers, device_id=args.local_rank,
	                       data_dir=train_dir, crop=crop_size, dali_cpu=False, args=args)
	pipe.build()
	train_loader = DALIClassificationIterator(pipe, size=int(pipe.epoch_size("Reader") / args.world_size))
	pipe = HybridValPipe(batch_size=args.test_batch_size, num_threads=args.workers, device_id=args.local_rank,
	                     data_dir=val_dir, crop=crop_size, size=val_size, args=args)
	pipe.build()
	val_loader = DALIClassificationIterator(pipe, size=int(pipe.epoch_size("Reader") / args.world_size))
	return train_loader, val_loader
```
Thanks,
Ema1997

**Comment by JanuszL** [comment] 2021-03-16 13:43
Hi,
It looks that n03928589/n03928589_1742.JPEG caused this problem. From the log, it seems that the image could be corrupted. Can you check if you can open the image successfully in any viewer?
If so can you attach it to the bug so we can reproduce the problem on our side?

**Comment by Ema1997** [comment] 2021-03-17 02:32
![n03928589_1742](https://user-images.githubusercontent.com/19912756/111404722-3eebde00-870a-11eb-820f-772d6484b38e.JPEG)
This image can be correctly opened in my computer's viewer, and I can load the ImageNet22k data using pytorch data backend. Therefore, I guess that the errors may not be caused by the data?

**Comment by JanuszL** [comment] 2021-03-17 11:16
Hi,
I will check with the nvJPEG (which DALI uses to accelerate JPEG decoding on the GPU) team where the problem is. In the meantime you can try to switch to the `cpu` based decoder.

**Comment by Ema1997** [comment] 2021-03-18 02:24
Ok, thanks.

**Comment by JanuszL** [comment] 2021-03-18 09:26
Hi @Ema1997.
I have added a fallback to the host decoder (CPU) in https://github.com/NVIDIA/DALI_extra/pull/52, so DALI can deal with such problem until nvJPEG adds support to the image that causes problems now.
Please check nightly/weekly build after the mentioned PR is merged to see if that helps with your issue.

**Comment by JanuszL** [comment] 2021-04-16 11:23
1.1.0 has been released. You can update and check if that works as you expect.

**Closed by JanuszL** 2021-04-16 11:23 UTC
Labels: bug
