### ISSUE TITLE
 how to solve " error: no matching function for call to 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit"

### ISSUE THREAD

**Issue by yhxuyou** [NVIDIA/DALI#1584] opened 2019-12-18 08:31 UTC
[ 21%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operator/op_schema.cc.o
[ 21%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operator/op_spec.cc.o
[ 22%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operator/operator.cc.o
[ 22%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/proto/dali_proto_intern.cc.o
[ 22%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/util/copy_with_stride.cc.o
[ 22%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/util/thread_pool.cc.o
[ 23%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/workspace/device_workspace.cc.o
[ 23%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/workspace/host_workspace.cc.o
[ 23%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/workspace/mixed_workspace.cc.o
[ 23%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/workspace/sample_workspace.cc.o
[ 24%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/init.cc.o
[ 24%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/pipeline.cc.o
[ 24%] Building CXX object dali/CMakeFiles/dali.dir/util/custream.cc.o
[ 24%] Building CXX object dali/CMakeFiles/dali.dir/util/file.cc.o
[ 25%] Building CXX object dali/CMakeFiles/dali.dir/util/image.cc.o
[ 25%] Building CXX object dali/CMakeFiles/dali.dir/util/local_file.cc.o
[ 25%] Building CXX object dali/CMakeFiles/dali.dir/util/npp.cc.o
[ 25%] Building CXX object dali/CMakeFiles/dali.dir/util/ocv.cc.o
[ 26%] Building CXX object dali/CMakeFiles/dali.dir/util/random_crop_generator.cc.o
[ 26%] Building CXX object dali/CMakeFiles/dali.dir/util/user_stream.cc.o
[ 26%] Building CXX object dali/CMakeFiles/dali.dir/util/nvml_wrap.cc.o
[ 26%] Building CXX object dali/CMakeFiles/dali.dir/plugin/plugin_manager.cc.o
[ 27%] Building CXX object dali/CMakeFiles/dali.dir/c_api/c_api.cc.o
/opt/data/xyz/dali-master/dali/pipeline/pipeline.cc: In constructor 'dali::Pipeline::Pipeline(const string&, int, int, int, bool, int, bool, std::size_t, bool, int, int)':
/opt/data/xyz/dali-master/dali/pipeline/pipeline.cc:75:58: error: no matching function for call to 'google::protobuf::io::CodedInputStream::SetTotalBytesLimit(std::__cxx11::basic_string<char>::size_type)'
     coded_input.SetTotalBytesLimit(serialized_pipe.size());
                                                          ^
In file included from /opt/data/xyz/dali-master/dali/pipeline/pipeline.cc:18:0:
/usr/local/include/google/protobuf/io/coded_stream.h:402:8: note: candidate: void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int, int)
   void SetTotalBytesLimit(int total_bytes_limit, int warning_threshold);
        ^
/usr/local/include/google/protobuf/io/coded_stream.h:402:8: note:   candidate expects 2 arguments, 1 provided
dali/CMakeFiles/dali.dir/build.make:585: recipe for target 'dali/CMakeFiles/dali.dir/pipeline/pipeline.cc.o' failed
make[2]: *** [dali/CMakeFiles/dali.dir/pipeline/pipeline.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:2048: recipe for target 'dali/CMakeFiles/dali.dir/all' failed
make[1]: *** [dali/CMakeFiles/dali.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target dali_core_test.bin
[ 28%] Building CXX object dali/core/CMakeFiles/dali_core_test.bin.dir/boundary_test.cc.o
[ 28%] Building CXX object dali/core/CMakeFiles/dali_core_test.bin.dir/byte_io_test.cc.o

my protobuf verison is 3.5.0,I dont know how to deal with this.

**Comment by awolant** [comment] 2019-12-18 14:33
Hi,
thanks for the question.
Internally, we test with [protobuf 3.11.1](https://github.com/NVIDIA/DALI/blob/master/docker/Dockerfile.deps#L37), so maybe good start would be to update to this version, if possible?
I've checked and it seems that API changed around this function. Probably we need to update required protobuf version.

**Comment by yhxuyou** [comment] 2019-12-19 02:36
> Hi,
> thanks for the question.
> Internally, we test with [protobuf 3.11.1](https://github.com/NVIDIA/DALI/blob/master/docker/Dockerfile.deps#L37), so maybe good start would be to update to this version, if possible?
> I've checked and it seems that API changed around this function. Probably we need to update required protobuf version.

thanks a lot,I have update protobuf to the latest version and deal with it

**Comment by awolant** [comment] 2019-12-20 09:51
#1586 is merged, closing. Please reopen, if the problem is still there.

**Closed by awolant** 2019-12-20 09:51 UTC
Labels: bug, question
