### ISSUE TITLE
The MP4 in  DALI_extra seems not a Video  File

### ISSUE THREAD

**Issue by SunGaofeng** [NVIDIA/DALI#1872] opened 2020-04-13 09:46 UTC
I've git cloned the repo of NVIDIA/DALI_extra. I want to do some test on the mp4 files.
In the directory, I found the file DALI_extra/db/video/test_label.mp4. But this file turns to be a txt file, not a video.  How can I get the MP4 video of this file?  

Here is the link for this file: 
https://github.com/NVIDIA/DALI_extra/blob/master/db/video/test_label.mp4

![image](https://user-images.githubusercontent.com/26536764/79110944-1fd42600-7dae-11ea-91cd-a3c77abab87f.png)

**Comment by SunGaofeng** [comment] 2020-04-14 03:42
I seems that I should install git LFS first. I did install Git LFS, however, git clone failed, which is similar to #1873   
I think this and #1873 can be combined into a issue.

Downloading db/MNIST/testing/data.mdb (9.0 MB)
Error downloading object: db/MNIST/testing/data.mdb (46b56bf): Smudge error: Error downloading db/MNIST/testing/data.mdb (46b56bf043f7c6938e4fc70ebb72c9f4fa959dacbf56f3745a0b0e45f82c6ce6): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /ssd2/sungaofeng/2020/q1/dali/gitlfs/DALI_extra/.git/lfs/logs/20200414T033740.399666317.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: db/MNIST/testing/data.mdb: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by JanuszL** [comment] 2020-04-14 06:43
Closing as a duplicate of https://github.com/NVIDIA/DALI/issues/1873. Thank you for reporting this.

**Closed by JanuszL** 2020-04-14 06:43 UTC

**Comment by JanuszL** [comment] 2020-05-20 21:36
Hi,
We have extended our quota. Please check now.
