### ISSUE TITLE
Critical error when run docs/example/tensorflow/demo/resnet.py

### ISSUE THREAD

**Issue by benzhang1986** [NVIDIA/DALI#297] opened 2018-11-14 06:28 UTC
Platform information:

Dali:                           0.4.1
CPU:                           Intel Xeon Gold 5117M 2.00 GHz x2
Memory:                   32Gx18+16Gx2
Disk:                           HDD
GPU:                          NVIDIA V100 (16GB) x 8
OS:                              Ubuntu 16.04
CUDA:                       9.0
CuDNN:                     7.3
Libnccl:                      2.2.13
Tensorflow:              1.10.0

run command:
mpiexec --allow-run-as-root --bind-to socket -np 8 python resnet.py --layers=50 --data_dir=/home/nvme/dataset/imagenet/tf_records/train/ --data_idx_dir=/home/nvme/dataset/imagenet/tf_records/idx_files/ --precision=fp16 --log_dir=/home/resnet50 --batch_size=128

error info:
  630   0.0  4716.7  4.766  5.244 1.97775
   640   0.0  4597.0  4.524  5.001 1.97740
   650   0.0  4707.2  4.737  5.213 1.97704
   660   0.0  4761.2  5.027  5.502 1.97669
   670   0.0  4682.6  4.501  4.974 1.97634
   680   0.0  4667.3  4.686  5.158 1.97599
   690   0.0  4773.2  4.425  4.896 1.97563
   700   0.0  4701.2  4.729  5.199 1.97528
   710   0.0  4723.1  4.490  4.958 1.97493
   720   0.0  4707.6  4.430  4.898 1.97457
   730   0.0  4755.1  4.649  5.116 1.97422
   740   0.0  4728.1  4.314  4.780 1.97387
   750   0.0  4657.8  4.459  4.924 1.97351
   760   0.0  4676.1  4.447  4.911 1.97316
   770   0.0  4668.6  4.622  5.085 1.97281
   780   0.0  4673.9  4.619  5.082 1.97246
   790   0.0  4737.2  4.735  5.197 1.97210
   800   0.0  4741.8  4.675  5.136 1.97175
   810   0.0  4583.5  4.586  5.047 1.97140
   820   0.0  4736.0  4.290  4.750 1.97104
   830   0.0  4663.9  4.468  4.927 1.97069
   840   0.0  4763.3  4.593  5.052 1.97034
   850   0.0  4687.6  4.071  4.530 1.96999
   860   0.0  4659.0  4.331  4.789 1.96963
   870   0.0  4694.3  4.411  4.869 1.96928
   880   0.0  4688.5  4.119  4.576 1.96893
   890   0.0  4648.0  4.413  4.870 1.96858
   900   0.0  4600.7  4.267  4.724 1.96822
   910   0.0  4661.6  4.234  4.690 1.96787
   920   0.0  4542.8  4.396  4.851 1.96752
   930   0.0  4581.3  4.050  4.506 1.96717
   940   0.0  4631.1  4.400  4.855 1.96681
   950   0.0  4694.8  4.296  4.750 1.96646
   960   0.0  4676.9  4.314  4.768 1.96611
   970   0.0  4674.6  4.031  4.485 1.96576

DALI daliShareOutput(&pipe_handle_) failed: Critical error in pipeline: Error in thread 1: [/opt/dali/dali/pipeline/operators/decoder/nvjpeg_decoder.h:349] NVJPEG error "3"
Current pipeline object is no longer valid.
Traceback (most recent call last):
  File "resnet.py", line 111, in <module>
    nvutils.train(resnet_v1, args)
  File "/home/z00417659/DALI-master/docs/examples/tensorflow/demo/nvutils/runner.py", line 266, in train
    hooks=training_hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1173, in _train_model_default
    saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1451, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 584, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1060, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1151, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1136, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1208, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 988, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: DALI daliShareOutput(&pipe_handle_) failed: Critical error in pipeline: Error in thread 1: [/opt/dali/dali/pipeline/operators/decoder/nvjpeg_decoder.h:349] NVJPEG error "3"
Current pipeline object is no longer valid.
         [[Node: Dali = Dali[device_id=1, image_type=DT_FLOAT, label_type=DT_INT64, num_threads=-1, serialized_pipeline="\010\002\0...77\377\001", shape=[128,224,224,3], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
         [[Node: total_loss/_4319 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_8042_total_loss", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'Dali', defined at:
  File "resnet.py", line 111, in <module>
    nvutils.train(resnet_v1, args)
  File "/home/z00417659/DALI-master/docs/examples/tensorflow/demo/nvutils/runner.py", line 266, in train
    hooks=training_hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1167, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1011, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1100, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/z00417659/DALI-master/docs/examples/tensorflow/demo/nvutils/runner.py", line 260, in <lambda>
    dali_cpu=dali_cpu, idx_filenames=train_idx_filenames)
  File "/home/z00417659/DALI-master/docs/examples/tensorflow/demo/nvutils/image_processing.py", line 161, in image_set
    deterministic=deterministic)
  File "/home/z00417659/DALI-master/docs/examples/tensorflow/demo/nvutils/image_processing.py", line 141, in __init__
    device_id=hvd.rank())
  File "<string>", line 75, in dali
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): DALI daliShareOutput(&pipe_handle_) failed: Critical error in pipeline: Error in thread 1: [/opt/dali/dali/pipeline/operators/decoder/nvjpeg_decoder.h:349] NVJPEG error "3"
Current pipeline object is no longer valid.
         [[Node: Dali = Dali[device_id=1, image_type=DT_FLOAT, label_type=DT_INT64, num_threads=-1, serialized_pipeline="\010\002\0...77\377\001", shape=[128,224,224,3], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
         [[Node: total_loss/_4319 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_8042_total_loss", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

2018-11-14 03:40:36.855149: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at mpi_ops.cc:302 : Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
2018-11-14 03:40:36.855394: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at mpi_ops.cc:302 : Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
2018-11-14 03:40:36.855447: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at mpi_ops.cc:302 : Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
2018-11-14 03:40:36.855594: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at mpi_ops.cc:302 : Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
2018-11-14 03:40:36.855588: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at mpi_ops.cc:302 : Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
2018-11-14 03:40:36.855693: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at mpi_ops.cc:302 : Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
2018-11-14 03:40:36.855698: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at mpi_ops.cc:302 : Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
2018-11-14 03:40:36.855767: W tensorflow/core/framework/op_kernel.cc:1275] OP_REQUIRES failed at mpi_ops.cc:302 : Unknown: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.

**Comment by JanuszL** [comment] 2018-11-14 11:40
Hi,
NVJPEG error "3" usually means that some image was not handled properly by nvJPEG because it is corrupted or there is a bug in the nvJPEG.
In 0.5 which will be released soon we added more verbose info about error root cause. In the mean time please check if this works with the HostDecoder, also whihc version of DALI do you use?
Tracked as DALI-360.

**Comment by benzhang1986** [comment] 2018-11-21 06:48
@JanuszL thank you for your answer.

I used DALI 0.4, this issue should caused by image corrupt in imagenet, the image file n02113799_2806.JPEG has bad data.

**Comment by JanuszL** [comment] 2018-11-21 08:05
Hi,
So I assume that after re-downloading n02113799_2806.JPEG everything works smoothy.

**Closed by JanuszL** 2018-11-21 08:05 UTC
Labels: bug, question
