### ISSUE TITLE
fn.lookup_table giving wrong result for gpu

### ISSUE THREAD

**Issue by SunXuan90** [NVIDIA/DALI#5254] opened 2023-12-25 12:17 UTC
### Version

1.31.0

### Describe the bug.

The operator works fine on cpu, but gives wrong output on gpu. 
Ubuntu 22.04, RTX 3080, Driver 535.129.03, CUDA 12.2
Running using nvcr.io/nvidia/pytorch:23.11-py3 docker image.
CPU code:
```python
import numpy as np
from nvidia.dali import fn, pipeline_def, types
from nvidia.dali.plugin.triton import autoserialize


@autoserialize
@pipeline_def(batch_size=64, num_threads=2, device_id=0)
def select_by_conf():
    raw = np.array([[0, 1, 2, 3]])
    ids = fn.external_source(source=raw, device="cpu")

    scale_keys = [0, 1]
    scale_values = [100, 200]
    scale_mat = fn.lookup_table(
        ids,
        keys=scale_keys,
        values=scale_values,
        device="cpu",
        dtype=types.INT64,
    )

    return scale_mat, ids


pipe = select_by_conf()
pipe.build()
out = pipe.run()
print(out)
```
CPU output:
```shell
(TensorListCPU(
    [100 200   0   0],
    dtype=DALIDataType.INT64,
    num_samples=4,
    shape=[(), (), (), ()]), TensorListCPU(
    [0 1 2 3],
    dtype=DALIDataType.INT64,
    num_samples=4,
    shape=[(), (), (), ()]))
```

GPU code:
```python
import numpy as np
from nvidia.dali import fn, pipeline_def, types
from nvidia.dali.plugin.triton import autoserialize


@autoserialize
@pipeline_def(batch_size=64, num_threads=2, device_id=0)
def select_by_conf():
    raw = np.array([[0, 1, 2, 3]])
    ids = fn.external_source(source=raw, device="cpu")
    ids = ids.gpu()

    scale_keys = [0, 1]
    scale_values = [100, 200]
    scale_mat = fn.lookup_table(
        ids,
        keys=scale_keys,
        values=scale_values,
        device="gpu",
        dtype=types.INT64,
    )

    return scale_mat, ids


pipe = select_by_conf()
pipe.build()
out = pipe.run()
print(out)
```
GPU output:
```shell
(TensorListGPU(
    [0 0 0 0],
    dtype=DALIDataType.INT64,
    num_samples=4,
    shape=[(), (), (), ()]), TensorListGPU(
    [0 1 2 3],
    dtype=DALIDataType.INT64,
    num_samples=4,
    shape=[(), (), (), ()]))
```

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment] 2023-12-27 07:20
Hi @SunXuan90,

I can confirm there is a problem with the GPU variant of that operator. Let us investigate it and get back to you with more info soon.

**Comment by jantonguirao** [comment] 2023-12-27 09:51
Hi @SunXuan90,

Thank you for reporting this bug. There are two problems with your code. The first one is an actual bug in the lookup table operator (we will fix it soon), and the second one is an issue with your code snippet. Let me explain.

[external_source](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.external_source.html#nvidia-dali-fn-external-source) `source` argument is meant for a callable or an iterable. In your case, you are feeding an iterable that it is interpreted as batches of data. The outermost dimension is interpreted as the number of batches (1 batch in your example) and the innermost dimension is interpreted as batch size (4 in your example). Since there are no more dimensions, each sample is assumed to be a scalar value (0-D). That is, you are processing a batch of 4 scalars. The bug in the GPU operator is when processing scalars (fix coming soon).

Now, I believe that your intention (correct me if I am wrong) was to apply a lookup table to a 2-dimensional matrix. Let me give you a couple of examples that do that:

First, using a 2D constant array, no need for external source:
```
        scale_mat = fn.lookup_table(
            np.array([[0, 1, 2, 3]]),
            keys=scale_keys,
            values=scale_values,
            device=device,
            dtype=types.INT64,
        )
```

Second, using a callable to generate batches of random data:
```
        def get_mat():
            out = [
                (np.random.randint(0, 4, size=(1, 4), dtype=np.int32))
                for _ in range(batch_size)
            ]
            return out
        ids = fn.external_source(source=get_mat, device=device)

        scale_mat = fn.lookup_table(
            ids,
            keys=scale_keys,
            values=scale_values,
            device=device,
            dtype=types.INT64,
        )
```

The good news is that processing 2D inputs should work, as the bug only applies to scalar inputs.

For the record, I'll let you know here when the fix is merged to the main branch.

**Comment by SunXuan90** [comment] 2023-12-27 12:34
Thank you!

**Comment by JanuszL** [comment] 2024-02-06 16:17
1.34 is out.

**Closed by JanuszL** 2024-02-06 16:17 UTC
Labels: bug
