### ISSUE TITLE
How to read unknown length array in tfrecord

### ISSUE THREAD

**Issue by ShiquanYu** [NVIDIA/DALI#2701] opened 2021-02-21 08:54 UTC
Hi,
I use dali to read tfrecord for object detection, the label number of per image is unknown(>0),
while i use the function `tfrec.FixedLenFeature` to read the tfrecord:
```python
class TFRecordPipeline(CommonPipeline):
    def __init__(self, batch_size, num_threads, device_id, num_gpus, tfrecord, tfrecord_idx):
        super(TFRecordPipeline, self).__init__(batch_size, num_threads, device_id)
        features = {
            'image_string': tfrec.FixedLenFeature((), tfrec.string, ""),
            'bboxes': tfrec.FixedLenFeature([], tfrec.float32, -1.0),
            'labels': tfrec.FixedLenFeature([], tfrec.int64, -1),
        }
        self.input = ops.TFRecordReader(path = tfrecord,
                                        index_path = tfrecord_idx,
                                        features = features)
```
it raise error:
```
/opt/conda/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py:121: Warning: Please set `reader_name` and don't set last_batch_padded and size manually  whenever possible. This may lead, in some situations, to miss some  samples or return duplicated ones. Check the Sharding section of the documentation for more details.
  _iterator_deprecation_warning()
Segmentation fault (core dumped)
```

In tensorflow, i can use the function `tf.io.FixedLenSequenceFeature` to read the unknown length array, how can i read unknown length array with dali like the function `tf.io.FixedLenSequenceFeature`?

**Comment by JanuszL** [comment] 2021-02-22 09:46
Hi,
The warning message is not related to the crash you see. Can you share any minimal subset of your data set which would reproduce the problem (I don't see anything wrong with your pipeline itself)?

**Comment by ShiquanYu** [comment] 2021-02-22 11:57
Hi @JanuszL ,

Thanks for your reply, the [test_set.zip](https://github.com/NVIDIA/DALI/files/6021673/test_set.zip) is my test set with 6 images from coco2017 and a tensorflow parser.

There are 2 list in feature while i made tfrecord:
```python
  feature={
      'image_string': _bytes_feature(image_string),
      'bboxes': _float_feature_list(ann['bboxes'].reshape(-1).tolist()),
      'labels': _int64_feature_list(ann['labels'].tolist())
  }
```
The list length(`bboxes` and `labels`) is unknown(different image has difference number of bounding boxes), so i need to use function `tf.io.FixedLenSequenceFeature` to parse them, but dali does not support this function. While i use `tfrec.FixedLenFeature` to parse the record, it raise error: `Segmentation fault (core dumped)`.

Is there any way to solve this problem?

Thank you.

**Comment by JanuszL** [comment] 2021-02-22 13:35
Hi,
Please try:
```
'bboxes': tfrec.VarLenFeature ([4], tfrec.float32, -1.0),
'labels': tfrec.VarLenFeature ([1], tfrec.int64, -1),
```
`VarLenFeature` supports partial shape (the data will be reshaped to match its value, and the first dimension will be inferred from the data size).

**Comment by JanuszL** [comment] 2021-02-22 16:11
I also added a check to prevent a crash in cases like yours - https://github.com/NVIDIA/DALI/pull/2705.

**Comment by ShiquanYu** [comment] 2021-02-23 02:47
Hi @JanuszL ,

It seems work after using `tfrec.VarLenFeature`, but it raise another error:
```
Traceback (most recent call last):
  File "dali_dataset/base.py", line 80, in <module>
    dali_iter = DALIGenericIterator(pipes, ['data', 'bboxes', 'labels'], pipes[0].epoch_size("Reader"))
  File "/opt/conda/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 160, in __init__
    self._first_batch = self.next()
  File "/opt/conda/lib/python3.7/site-packages/nvidia/dali/plugin/base_iterator.py", line 270, in next
    return self.__next__()
  File "/opt/conda/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 187, in __next__
    category_tensors[category] = out.as_tensor()
RuntimeError: [/opt/dali/dali/pipeline/data/tensor_list.h:567] Assert on "this->IsDenseTensor()" failed: All tensors in the input TensorList must have the same shape and be densely packed.
```
I see DALI doesn't support variable-length data in PyTorch in this [issue comment #2007](https://github.com/NVIDIA/DALI/issues/2007#issuecomment-640577492),  Is there any other ways to read variable-length data in PyTorch?

Here is my code:
```python
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import cv2
import numpy as np
import nvidia.dali.tfrecord as tfrec

class CommonPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(CommonPipeline, self).__init__(batch_size, num_threads, device_id)

        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.resize = ops.Resize(device="gpu",
                                 interp_type=types.INTERP_LINEAR,
                                 size=320)
        self.uniform = ops.Uniform(range = (0.0, 1.0))
        self.box_enc = ops.BoxEncoder(
            device="cpu",
            criteria=0.5,
            anchors=[0, 0, 1, 1]
        )
        self.cast_int32 = ops.Cast(device="cpu", dtype=types.INT32)

    def base_define_graph(self, inputs, bboxes, labels):
        images = self.decode(inputs)
        images = self.resize(images)
        output = images
        enc_bboxes, enc_labels = self.box_enc(bboxes, self.cast_int32(labels))
        # return (output, enc_bboxes, enc_labels)
        return (output, bboxes, labels)


class TFRecordPipeline(CommonPipeline):
    def __init__(self, batch_size, num_threads, device_id, num_gpus, tfrecord, tfrecord_idx):
        super(TFRecordPipeline, self).__init__(batch_size, num_threads, device_id)
        features = {
            'image_string': tfrec.FixedLenFeature((), tfrec.string, ""),
            'bboxes': tfrec.VarLenFeature([4], tfrec.float32, -1.0),
            'labels': tfrec.VarLenFeature([], tfrec.int64, -1),
        }
        self.input = ops.TFRecordReader(path = tfrecord,
                                        index_path = tfrecord_idx,
                                        features = features)

    def define_graph(self):
        inputs = self.input(name="Reader")
        images = inputs["image_string"]
        bboxes = inputs["bboxes"]
        labels = inputs["labels"]
        return self.base_define_graph(images, bboxes, labels)

if __name__ == '__main__':
    import numpy as np
    from nvidia.dali.plugin.pytorch import DALIGenericIterator
    BATCH_SIZE = 2
    N = 1
    tfrecord = 'coco_test.tfrecord'
    tfrecord_idx = 'coco_test.idx'
    pipes = [
        TFRecordPipeline(tfrecord = tfrecord,
                         tfrecord_idx = tfrecord_idx,
                         batch_size=BATCH_SIZE,
                         num_threads=2,
                         device_id=device_id,
                         num_gpus=N) for device_id in range(N)
    ]
    pipes[0].build()
    dali_iter = DALIGenericIterator(pipes, ['data', 'bboxes', 'labels'], pipes[0].epoch_size("Reader"))
    for i, data in enumerate(dali_iter):
        for d in data:
            images = d["data"].cpu().numpy()
            bboxes = d["bboxes"].cpu().numpy()
            labels = d["labels"].cpu().numpy()
            for image, bboxe, label in zip(images, bboxes, labels):
                print(bboxe)
                print(label)
                print(image.shape)
                cv2.imshow("img", image[..., ::-1])
                if cv2.waitKey(0) == ord('q'):
                    exit()
```

**Comment by JanuszL** [comment] 2021-02-23 09:12
Hi @ShiquanYu,

In this case, you can use BoxEncoder and output tensor batch convertible to just one PyTorch tensor.
Another option (although not recommended due to performance reasons) is to use a batch size of 1.
The last one, is to use pad operator and return the real shapes before padding:
```
class CommonPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(CommonPipeline, self).__init__(batch_size, num_threads, device_id)

        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.resize = ops.Resize(device="gpu",
                                 interp_type=types.INTERP_LINEAR,
                                 size=320)
        self.uniform = ops.Uniform(range = (0.0, 1.0))
        self.box_enc = ops.BoxEncoder(
            device="cpu",
            criteria=0.5,
            anchors=[0, 0, 1, 1]
        )
        self.cast_int32 = ops.Cast(device="cpu", dtype=types.INT32)
        self.pad = ops.Pad()
        self.shape = ops.Shapes()

    def base_define_graph(self, inputs, bboxes, labels):
        images = self.decode(inputs)
        images = self.resize(images)
        output = images
        enc_bboxes, enc_labels = self.box_enc(bboxes, self.cast_int32(labels))
        # return (output, enc_bboxes, enc_labels)
        bboxes_shape = self.shape(bboxes)
        bboxes = self.pad(bboxes)
        labels_shape = self.shape(labels)
        labels = self.pad(labels)
        return (output, bboxes, labels, bboxes_shape, labels_shape)
```
The last one is to provide a custom implementation of DALIGenericIterator for PyTorch starting from [here](https://github.com/NVIDIA/DALI/blob/master/dali/python/nvidia/dali/plugin/pytorch.py).

**Comment by ShiquanYu** [comment] 2021-02-23 12:01
Hi @JanuszL ,

Thanks for your apply, after several tests, I decided to pad the bbox&labels T^T

Thank you vvvvery much for your patience to answer my questions~

**Closed** 2021-02-23 12:08 UTC
Labels: question
