### ISSUE TITLE
test_operator_python_function.py fails on Linux RHEL 7.7 x86 and ppc64le

### ISSUE THREAD

**Issue by npanpaliya** [NVIDIA/DALI#1750] opened 2020-02-20 10:45 UTC
test_operator_python_function.py also fails for the conda package built for DALI 0.13, 0.17 and 0.18 and even the 0.19.0-dev. For some reason the SinkTestPipeline fails with jpg images. It can not save the same number of files as that of BATCH_SIZE. But if I change the test for png files, it passes. Even for .tiff files, it fails.
```
======================================================================
FAIL: test_operator_python_function.test_sink
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/anaconda3/envs/testdalinew/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/builder/DALI/dali/test/python/test_operator_python_function.py", line 442, in test_sink
    assert len(created_files) == BATCH_SIZE
AssertionError:
```

**Comment by npanpaliya** [comment] 2020-02-20 11:04
This issue is seen on both Power and x86 architectures.

**Comment by JanuszL** [comment] 2020-02-20 13:19
I'm not able to reproduce this problem with bare-metal build, nor the internal conda build.
I have such packages installed in my test conda env - 
[list.txt](https://github.com/NVIDIA/DALI/files/4230868/list.txt)
And I gets:
```
(conda_py36_env) jlisiecki@jlisiecki-dt1:~/Dali/dali/dali/test/python$ nosetests --verbose test_operator_python_function.py:test_sink
test_operator_python_function.test_sink ... read 47 files from 19 directories
ok

----------------------------------------------------------------------
Ran 1 test in 0.369s

OK
```
Can you try to run this particular test case form python - you need to add a call to `test_sink()` function somewhere and see what it says (it should print all files created)? You can also add some extra print to the `save(image)` function as well.

**Comment by JanuszL** [comment] 2020-02-20 13:20
But I have tested that in Ubuntu, not RHEL 7.7.

**Comment by npanpaliya** [comment] 2020-02-20 13:55
@JanuszL - Thank you for suggesting me to try with python. At least it threw a warning regarding time.clock() being deprecated. So, I replaced that with time.process_time() and I got the test run successfully with DALI 0.20.
I've created a PR https://github.com/NVIDIA/DALI/pull/1752 to fix this in DALI.

**Comment by JanuszL** [comment] 2020-03-31 07:09
DALI 0.20 is out. and should include a fix for this bug. Closing.

**Closed** 2021-04-14 15:52 UTC
Labels: IBM, bug
