### ISSUE TITLE
Segmentation Fault when using Optical Flow with large Batch size

### ISSUE THREAD

**Issue by castim** [NVIDIA/DALI#2912] opened 2021-04-30 09:18 UTC
Hi, 

When I run the following code

```python
from tqdm import tqdm

from nvidia import dali
import nvidia.dali.fn as fn

@dali.pipeline_def
def video_pipeline():
    seq = fn.readers.video(device="gpu", filenames="sintel_trailer-1080p-g5.mp4", sequence_length=3)
    flows = fn.optical_flow(seq, output_format=4)
    return flows

pipe = video_pipeline(batch_size=16, num_threads=1, device_id=0)

pipe.build()

for i in tqdm(range(99999999)):
    pipe.run()
```
I always get a segmentation fault after 30~300 iterations. Is it because this batch size is too big?
```
Segmentation fault (core dumped) 
```

I use the [sintel trailer 1080p](https://download.blender.org/durian/trailer/sintel_trailer-1080p.mp4) which I reencoded to get a smaller gop size with:
```
ffmpeg -i sintel_trailer-1080p.mp4 -g 5 sintel_trailer-1080p-g5.mp4
```

I use DALI 1.1.0 with cuda 11.

**Comment by JanuszL** [comment] 2021-04-30 09:25
Hi,

It is not related to the batch size. Let us find the root cause and get back to you soon.

**Comment by JanuszL** [comment] 2021-04-30 09:40
@castim,

Can you tell what GPU and driver version do you have?

**Comment by castim** [comment] 2021-04-30 09:53
I have the same problem on a RTX 3090 with driver 465.19.01 and on a Tesla T4 also with 465.19.01

**Comment by JanuszL** [comment] 2021-04-30 09:54
I'm not able to reproduce this on the 450.x driver while it happens on 465.x. It seems to be unrelated to DALI itself. Let us check with the relevant team.

**Comment by mzient** [comment] 2021-04-30 11:14
@castim Apparently there's a problem with running Optical Flow on non-default stream (in the affected driver). A workaround #2914 should fix it. Check the next nightly build after the workaround is merged.

**Comment by castim** [comment] 2021-04-30 11:38
Great, will check that. Thank you!

**Comment by JanuszL** [comment] 2021-07-06 05:10
The fix (workaround) has been included in the most recent release.

**Closed by JanuszL** 2021-07-06 05:10 UTC
Labels: bug
