### ISSUE TITLE
Core dumped while processing ops.Rotate() of 40000 * 40000 large scale medical images

### ISSUE THREAD

**Issue by Huangyuren** [NVIDIA/DALI#2588] opened 2021-01-05 09:08 UTC
Hi,
Currently I am processing on large scale whole slide images which are read from another library called OpenSlide. 
Here I utilize external source pipeline to bridge OpenSlide with DALI pipeline.
I encountered CUDAError while trying to rotate images with 40000 * 40000 * 3 dimension in DALI pipeline, and here is my code.
## Code
```
import torch
from torch.utils import data
import nvidia.dali.ops as ops
import nvidia.dali.types as types
from nvidia.dali.pipeline import Pipeline
import numpy as np
import os
import scipy.misc
import time
import argparse
import openslide
import cv2
from PIL import Image

parser = argparse.ArgumentParser()
parser.add_argument("--path", type=str, help="image dir for openslide", default='./data/')
parser.add_argument("--resize_ratio", type=float, help="resize ratio", default=0.2)
parser.add_argument("--img_size", type=int, help="image size", default=40000)
parser.add_argument("--iters", type=int, help="number of iterations", default=1)
parser.add_argument("--batch_size", type=int, help="batch size", default=2)
args = parser.parse_args()

class InputDataset(data.Dataset):
    def __init__(self, batch_size, slide_path, resize_ratio, img_size):
        self.slide_path = slide_path
        self.resize_ratio = resize_ratio
        self.img_size = img_size
        self.file_labels = []
        self.batch_size = batch_size
        classes = []
        image_dir = os.path.normpath(slide_path)
        label_i = 0
        for r, d, f in os.walk(image_dir):
            if r == image_dir:
                classes = d
            if os.path.dirname(r) == image_dir:
                f = sorted(f)
                path_f = [os.path.join(r, name) for name in f]
                self.file_labels += zip(path_f, len(f) * [label_i])
                label_i += 1
        for labels in self.file_labels:
            print("", labels)

    def __len__(self):
        return len(self.file_labels)

    def __getitem__(self, index):
        return self._load_img(index)

    def _load_img(self, index):
        # Here we load in one (40000, 40000, 3) medical image, since self.img_size is 40000, each pixel with rgb channels.
        # For reproducible result, it should be fine to use fake generated images with shape (40000, 40000, 3) instead.
        img = img[: self.img_size, : self.img_size, :]
        return img

class ExternalSourcePipeline(Pipeline):
    def __init__(self, source, batch_size, num_threads, device_id):
        super(ExternalSourcePipeline, self).__init__(batch_size, num_threads, device_id, seed=12)
        self.source = source
        self.source_iter = iter(source)
        self.input = ops.ExternalSource()
        self.res_rotate = ops.Rotate(device="gpu", angle=30.0, fill_value=255.0, keep_size=True)

    def define_graph(self):
        self.srcimages = self.input()
        images = self.srcimages.gpu()
        images = self.res_rotate(images)
        return images

    def iter_setup(self):
        p = self.source_iter.next()
        images = p
        self.feed_input(self.srcimages, images)

slide_loader = InputDataset(
    batch_size = args.batch_size,
    slide_path=args.path,
    resize_ratio=args.resize_ratio,
    img_size=args.img_size,
)
dataset_loader = data.DataLoader(slide_loader, batch_size=args.batch_size, shuffle=False, \
                        num_workers=2, pin_memory=False, drop_last=True)
pipe = ExternalSourcePipeline(source=dataset_loader, batch_size=args.batch_size, num_threads=4, device_id=0)
pipe.build()
for i in range(len(slide_loader) // args.batch_size):
    try:
        pipe_out = pipe.run()  # CUDAError at here
        img_tensor = pipe_out.__getitem__(0)
        # img_tensor = img_tensor.as_cpu()
        # img_tensor = img_tensor.as_array()
        # print("Shape of img_tensor: ", img_tensor.shape)
        # for j in range(args.batch_size):
        #     img_single_tensor = np.reshape(img_tensor[j], (args.img_size, args.img_size, 3))
        #     print("Pipe out idx: {}-{}, shape = {}".format(i, j, img_single_tensor.shape))
        #     imagetmp = Image.fromarray(img_single_tensor)
        #     imagetmp.save('./results/outfile-{}-{}.jpg'.format(i, j))
    except StopIteration:
        print("Dataset reaches the end.")
        break
```
## Outputs
```
Traceback (most recent call last):
  File "./src/daliExternalSrc.py", line 136, in <module>
    pipe_out = pipe.run()
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 734, in run
    return self.outputs()
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 633, in outputs
    return self._outputs()
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 717, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:
CUDA runtime API error cudaErrorIllegalAddress (700):
an illegal memory access was encountered
Current pipeline object is no longer valid.
terminate called after throwing an instance of 'dali::CUDAError'
  what():  CUDA runtime API error cudaErrorIllegalAddress (700):
an illegal memory access was encountered
./simpleProfile.sh: line 20:  3113 Aborted                 (core dumped) python ./src/daliExternalSrc.py --iters $1 --path $2 --resize_ratio 0.2 --img_size 40000 --batch_size 1
```
## Machine environments
Super computer -- Taiwania-2
* OS: Ubuntu 18.04
* host ram: 754GB ddr4
* nvcc --version: cuda_11.1
* GPU: NVIDIA Tesla V100-SXM2 (32G)
* CPU: Intel(R) Xeon(R) Gold 6154

This code works fine when images height & width in ```_load_img()``` are resized to (20000, 20000) or other lower dimensions. I used single gpu to do this pipeline and the GPU VRAM is enough given that 40000 * 40000 * 3 required only 4.8GB for each image (I verified this by nsight system profiling).
Error messages shown that it may not be gpu's fault; would it be too large tensor for DALI to afford, and the pipeline accidentally dropped this 40000 * 40000 * 3 gpu-tensor before pop-out ?!

## Pics from nsight system -- Normal case
Showing that experiment shape with (20000, 20000, 3) works fine with DALI pipeline. All 6 images being loaded in, rotated then stored back to disk.
* batch size: 1
* img_size: 20000
![IMG_4F2D1F86FA50-1](https://user-images.githubusercontent.com/37345266/103626734-96860480-4f77-11eb-8778-cac1a6222d82.jpeg)

Thanks for your support!

**Comment by jantonguirao** [comment] 2021-01-05 11:10
We were able to reproduce the problem. We'll investigate. Thanks!

**Comment by JanuszL** [comment] 2021-01-07 12:59
Hi,
Just checked thoroughly the issue.
There are several sources of memory allocation in DALI, in this case:
- by default DALI uses double buffering, so you need to reserve at least 2x 4.7GB for the output itself
- DALI maintains a persistent buffer between each operator - so you have an additional one between ExternalSource and Rotate on the GPU -  4.7GB
- as DALI has CPU, Mixed, and GPU stages that are independent it needs to keep the same number of buffer at the boundary of each stage as for the output. So the buffer that is between ExternalSource and Rotate need to have an additional copy

So in your pipeline, you will have 4x 4.7 GB memory required. Setting `prefetch_queue_depth=1` in the pipeline constructor make the memory requirement only 2x 4.7GB. We are working on improving the memory allocation schema and reduce the memory pressure, but this is a long-term effort and in your particular use case it may not yield many benefits.

However this doesn't address the issue you see. We will get back to you when we root cause it.

**Comment by mzient** [comment] 2021-01-11 08:13
@Huangyuren @JanuszL Surface object, which is used by all warp-family operator uses a vector dot product to calculate the offset. Dot product does not promote the type to a larger one, so the resulting offset is a 32-bit integer, which limits the surfaces to 2G elements. Even if we replace dot product with something more appropriate, still the strides are limited to 32 bits, which would make it impossible to hold a tensor with slices larger than 2G. The first problem we should fix, as for the latter - I'm not convinced, since increasing the size of the surface structure may have adverse effect on performance while 2G limit per slice is still acceptable for the vast majority of use cases.

**Comment by Huangyuren** [comment] 2021-01-12 06:16
Hi @JanuszL , thanks for explanations on memory footprint. I have several questions to clarify.
For example, assuming that we have operators placed in this order: 
1. ExternalSource (cpu)
2. Flip (gpu)
3. Rotate (gpu)

with ```prefetch_queue_depth=3```, there are 3x 4.7 GB for pipeline triple buffering, 2x 4.7 GB between these 3 operators respectively, and 2x 4.7 GB additional copies for keeping buffers at each stage boundary which are between ExternalSource and Flip. So in this pipeline, we have 7x 4.7 GB memory required, right?
Besides, I can observe double buffering on nsight system profiling, but seems to miss other buffers(persistent & stage boundary). Will these buffers also show on profiling timelines or just simply be summed up and show in ```memory usage``` in nvidia-smi ?
Thanks!

**Comment by mzient** [comment] 2021-01-12 09:20
@Huangyuren Fixed in #2600. Should be there in tomorrows nightly build.

**Comment by JanuszL** [comment] 2021-01-12 09:55
Hi in the mentioned case you will have:
- 3x GPU buffer between ExternalSource and Flip 
- 1x GPU bugger between Flip and Rotate 
- 3x GPU buffers for the output

>Besides, I can observe double buffering on nsight system profiling, but seems to miss other buffers(persistent & stage boundary). Will these buffers also show on profiling timelines or just simply be summed up and show in memory usage in nvidia-smi ?

What you should be able to observe is when you call `run()` and then wait DALI should run 3 times and make 3 sets of batches ready to be consumed. That is what you should observe in the profiler. Besides that, I don't think you can observe the buffers themselves in the timeline, only DALI operations. Buffers themselves are only to make prefetching possible.

**Comment by Huangyuren** [comment] 2021-01-12 19:51
@mzient restriction of int32 for avoiding performance degradation sounds reasonable, your PR may help me a lot, I will try this nightly build tomorrow, thanks !

**Comment by JanuszL** [comment] 2021-01-30 00:41
DALI 0.30 has been released and should address your issue.

**Closed by JanuszL** 2021-01-30 00:41 UTC
Labels: bug
