### ISSUE TITLE
Does ops.VideoReader support the .avi video format? 

### ISSUE THREAD

**Issue by csimo005** [NVIDIA/DALI#1169] opened 2019-08-15 21:03 UTC
Im using the example code for a video loader found in the tutorial here: https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/video/video_reader_label_example.html 

however, I am trying to use it to read the UCF101 dataset, which uses the .avi file format not .mp4 and I am not able to open the videos.

Does the VideoReader support avi videos or is this more likely caused by something else on my system?

**Comment by Kh4L** [comment] 2019-08-15 23:58
Hi @csimo005 ,
Avi is not a codec but a container format. The VideoReader op uses FFMpeg for opening and demultiplexing, which (normally) support Avi.

[In the dataset paper](https://arxiv.org/pdf/1212.0402.pdf) I can read that " The videos are saved in .avi files compressed using DivX codec available in k-lite package", and AFAIK VideoReader currently doesn't support this DivX.

**Comment by JanuszL** [comment] 2019-08-19 14:29
As @Kh4L correctly pointed out Nvidia NVDEC support Xvid/DivX formats, but currently DALI fails to properly seek on this container (at least one I have tested from UCF101). Adding to our ToDo list.

**Comment by a-sansanwal** [comment] 2019-08-23 19:38
With some work, I was able to decode some videos in this dataset.

However you will still not be able to decode all the videos in the dataset currently. 
This is caused by three issues.

1.  DALI build did not enable avi demuxer for ffmpeg. 
This can be fixed easily  [[Patch](https://github.com/a-sansanwal/DALI/commit/7f70165a57fba3a2e632803f963df76c097cf951)]. 
2. Packed b-frames in xvid/divx videos [[info](http://itsjustonesandzeros.blogspot.com/2007/01/what-is-packed-bitstream.html)]. 
This is a quirk. Fortunately there is a ffmpeg bitstream filter that exists for this exact problem [[documentation](https://www.ffmpeg.org/ffmpeg-bitstream-filters.html#mpeg4_005funpack_005fbframes)]. However just using this bitstream filter in DALI code did not fix the issue for some reason.  
The other way to solve this is to run the following command in UCF-101 root folder and that did the trick. This command remuxes all the files and should take a few minutes.
```
find . -maxdepth 2 -type f -exec  sh -c "ffmpeg -i {} -codec copy -bsf:v mpeg4_unpack_bframes tmp.avi && mv tmp.avi {}"  \;
```
3. Variable frame rate on some files in the dataset. 
Currently DALI does not support decoding vfr.

So in essence, you should be able to decode all videos except those with variable frame rate.

**Comment by awolant** [comment] 2019-10-01 16:14
Support was merged, so I'm closing this issue. Please reopen, if you encounter more problems with this.

**Closed by awolant** 2019-10-01 16:14 UTC
Labels: Video, enhancement
