### ISSUE TITLE
memory use continuously increasing

### ISSUE THREAD

**Issue by zsz00** [NVIDIA/DALI#4675] opened 2023-02-23 09:49 UTC
This task is video classification training on kinetics400 dataset.
I use DALI with pytorch to load videos for train kinetics400. 

Training set is 230,000 10-second video clips, and dali is used for video loading. 
During the training process, the memory usage continues to increase, 1.0 epoch to 94%, about 1.5 epoch to OOM.

The memory of the training host is 380G. GPU: nvidia-3090 *8, disk: ssd
I'm using Nvidia Dali 1.22.0, with ubuntu 18.04, cuda11.0, cudnn7.4.1, pytorch v1.12.1

```
@pipeline_def
def video_pipe_2(filenames, labels, sequence_length=10, random_shuffle=False, preset="fastest_speed", stride=1, shard_id=0, num_shards=1):
    video, labels = fn.readers.video(device="gpu", filenames=filenames, sequence_length=sequence_length, labels=labels,
                             shard_id=shard_id, num_shards=num_shards, random_shuffle=random_shuffle, initial_fill=10,
                             skip_vfr_check=True, pad_sequences=True, pad_last_batch=False, name="Reader",
                             file_list_include_preceding_frame=False, prefetch_queue_depth=2)
    resize_dims = [256, 256]
    resize_dims_2 = [224, 224]
    video = fn.resize(video, size=resize_dims)
    video = fn.random_resized_crop(video, size=resize_dims_2, random_area=[0.08, 1.0])

        video = fn.crop_mirror_normalize(
                video, crop_w=224, crop_h=224, output_layout="CFHW",
                mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375])
        # video = fn.transpose(video, perm=[3, 0, 1, 2])  # NCTHW

        return video, labels

pipe = video_pipe_2(filenames=video_list, labels=labels, sequence_length=64, 
                            random_shuffle=True, batch_size=batch_size, num_threads=4,
                            device_id=loacl_rank, shard_id=loacl_rank, num_shards=world_size)
pipe.build()
dali_loader = pytorch.DALIGenericIterator(pipe, output_map=["frames", "labels"], reader_name="Reader", auto_reset=True)

epoch = 10
for k in range(epoch):
    for i, batch in enumerate(dali_loader):
        if i % 100 == 0:
            print(k, i, batch[0]["frames"].shape, batch[0]["labels"].shape)

```

The issue seem to #4256 

the suggestions in #486, #278 not solved my problem. 

![image](https://user-images.githubusercontent.com/12711073/220874743-5d5c76fb-f9d0-4ae6-8a7f-b33c6b92e265.png)

data describe:  234195 rows
![image](https://user-images.githubusercontent.com/12711073/220893307-9d995934-bb52-4865-8c8f-c7b1434c3f9d.png)

**Comment by JanuszL** [comment] 2023-02-23 10:46
Hi @zsz00,

Thank you for reaching out. Can you try [the fused `readers.video_resize`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.video_resize.html) operator (as I understand the OOM happens for the GPU memory)? Now DALI needs to decode the whole batch in the full resolution just to downscale it later, but still, it requires a full buffer used between the decoder and resizes operator that can be removed if the fused variant is used.
Due to the random nature of the processing for training, it may happen that a given iteration just needs more memory, still, the memory consumption should stabilize after a couple of epochs.

**Comment by zsz00** [comment] 2023-02-24 03:21
The seem  issue https://github.com/NVIDIA/DALI/issues/4256 hasn't been solved yet.

**Comment by JanuszL** [comment] 2023-02-24 11:27
Another idea that comes to my mind is that it may be OOM due to memory fragmentation. When you use a video decoder it creates the context for each video file in the data set (and with hundreds of thousands of videos it can be a lot). What you may try to do is to assign to each DALI instance only a subset of all files and see if that helps. In this case, each DALI instance will get:
```
pipe = video_pipe_2(filenames=video_list[int(loacl_rank/world_size*len(video_list)):int((loacl_rank+1)/world_size*len(video_list))],
                            labels=labels[int(loacl_rank/world_size*len(labels)):int((loacl_rank+1)/world_size*len(labels))],
                            sequence_length=64, 
                            random_shuffle=True, batch_size=batch_size, num_threads=4,
                            device_id=loacl_rank, shard_id=0, num_shards=1)```
In the meantime, I run your pipeline using the data from https://github.com/NVIDIA/DALI_extra/tree/main/db/video/sintel/video_files and I was unable to reproduce the CPU memory growth. Can you provide a minimal repro we can run on our side?

**Comment by zsz00** [comment] 2023-02-24 15:51
[dali_test_min.txt](https://github.com/NVIDIA/DALI/files/10825991/dali_test_min.txt)

export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python -m torch.distributed.launch --nproc_per_node=8 --master_addr="127.0.0.1" --master_port=29501 dali_test_min.py

**Comment by JanuszL** [comment] 2023-02-24 17:03
Let me download the data set and see the results I get on my side.

**Comment by JanuszL** [comment] 2023-03-01 09:28
I think this might help - https://github.com/NVIDIA/DALI/pull/4682. It seems that libaviutil buffers the data for further use, and it is more than 200KB per file. The mentioned PR releases this data and it should bring the host memory consumption under control.

**Comment by stiepan** [comment] 2023-04-12 11:47
DALI 1.24 with the fix has been released. You can check it out here: https://github.com/NVIDIA/DALI/releases/tag/v1.24.0

**Comment by JanuszL** [comment] 2023-04-12 11:47
1.24 has been released. Please check it and reopen it if it still doesn't work.

**Closed by stiepan** 2023-04-12 11:47 UTC
Labels: help wanted
