### ISSUE TITLE
OSError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by qiuhaining** [NVIDIA/DALI#2080] opened 2020-07-02 07:34 UTC
pytorch 1.5
dali0.23

 from nvidia.dali.plugin.pytorch import DALIGenericIterator as PyTorchIterator
The error is：
OSError: dlopen: cannot load any more object with static TLS

**Comment by JanuszL** [comment] 2020-07-02 09:42
Hi,
Could you provide more info how to reproduce your problem?
In my case:
```
nvidia-dali-cuda110           0.23.0
torch                                   1.5.1
python -c "from nvidia.dali.plugin.pytorch import DALIGenericIterator as PyTorchIterator"
```
works fine.

**Comment by JanuszL** [comment] 2020-07-02 09:47
Also what OS you have?

**Comment by qiuhaining** [comment] 2020-07-02 10:31
Sorry,it's my details:
`
nvidia-dali-cuda110           0.23.0
torch                         1.5.0`
os                              Ubuntu 14.04.5 LTS

When，i run this example，the error occurred 
[https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-basic_example.html](url)
`
Traceback (most recent call last):
  File "dali_pytorch.py", line 86, in <module>
    from nvidia.dali.plugin.pytorch import DALIGenericIterator as PyTorchIterator
  File "/home1/qiushi/anaconda3/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 18, in <module>
    import torch
  File "/home1/qiushi/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 137, in <module>
    _load_global_deps()
  File "/home1/qiushi/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 95, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home1/qiushi/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen: cannot load any more object with static TLS
`

**Comment by JanuszL** [comment] 2020-07-02 11:05
Is upgrading to 16.04 or later is an option for you? There is a similar issue https://github.com/tensorflow/models/issues/523#issuecomment-533241126 resolved by the upgrade.

**Comment by klecki** [comment] 2020-07-02 11:24
From what I can see it's boils down to glibc's support of TLS and the limit for static TLS slots, which was raised around during the time of Ubuntu 14.04: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793641

Can you check what glibc version your system has?

**Comment by qiuhaining** [comment] 2020-07-02 11:27
> From what I can see it's boils down to glibc's support of TLS and the limit for static TLS slots, which was raised around during the time of Ubuntu 14.04: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793641
> 
> Can you check what glibc version your system has?

hi! my system's glibc is 2.19

**Comment by klecki** [comment] 2020-07-02 11:30
> hi! my system's glibc is 2.19
That would match the bug report that I posted above. In newer versions they seem to have raised the limit from 14 to 64 slots for static TLS. Unfortunately, we can't remove the static TLS usage from DALI now due to compatibility issues when linking other static libraries.

**Comment by qiuhaining** [comment] 2020-07-02 11:33
> > hi! my system's glibc is 2.19
> 
> That would match the bug report that I posted above. In newer versions they seem to have raised the limit from 14 to 64 slots for static TLS. Unfortunately, we can't remove the static TLS usage from DALI now due to compatibility issues when linking other static libraries.

Do you know which version of Dali can match my system?Thank you

**Comment by klecki** [comment] 2020-07-02 11:38
We added the TLS workaround in DALI 0.23.0, so you can try using DALI 0.22.0 where it was not present yet.

**Comment by JanuszL** [comment] 2021-04-23 18:32
The problematic code was just removed in https://github.com/NVIDIA/DALI/pull/2879.
You can test the next nightly build and see if that helps.

**Comment by JanuszL** [comment] 2021-05-25 21:54
Hi,
DALI 1.2 has been released and should fix the issue.

**Closed by JanuszL** 2021-05-25 21:54 UTC
Labels: bug
