### ISSUE TITLE
Shuffle images with ops.ExternalSource() 

### ISSUE THREAD

**Issue by addisonklinke** [NVIDIA/DALI#700] opened 2019-03-26 18:55 UTC
**Short Version:** I am feeding images and bounding boxes to my pipeline from a custom class using `ops.ExternalSource()`. When training a network, I want to shuffle the order of images each epoch. Is there a simple way to accomplish this?

Requirements for the custom loader
* _Must_ use `ops.ExternalSource()`. The actual dataset is very large and I don't want to re-format it to match the available readers (i.e. MXNet, TFRecord, Caffe2, etc.)
* Should be re-usable across epochs (i.e. doesn't ever raise `StopIteration`)
* Does not repeat images within an epoch and includes all images every epoch

**Long Version:** Below is my attempt at a custom loader class to achieve this

```
import os
from pickle import load
import random
import numpy as np

class ShuffleLoader():
    """Load images and bounding boxes from filepath."""
    def __init__(self, img_dir, batch_size, shuffle=True):
        self.img_dir = img_dir
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.imgs = [os.path.join(self.img_dir, f) for f in os.listdir(self.img_dir)]
        pkl_file = os.path.join(self.img_dir, 'dali-meta.pkl')
        with open(pkl_file, 'rb') as f:
            self.meta = load(f)
        self.idxs = []

    def __call__(self):
        jpegs = []
        bboxes = []
        for _ in range(self.batch_size):
            img_path = self.imgs[self.get_idx()]
            img_name = img_path.split('/')[-1]
            metadata = self.meta[img_name]
            with open(img_path, 'rb') as f:
                jpegs.append(np.frombuffer(f.read(), dtype=np.uint8))
            bboxes.append(metadata['corners'])
        return jpegs, bboxes

    def get_idx(self):
        if len(self.idxs) == 0:
            self.idxs = list(range(len(self.imgs)))
            if self.shuffle:
                random.shuffle(self.idxs)
        return self.idxs.pop()
```
Explanation
* JPEG images are in a folder with a pickled dictionary `dali-meta.pkl` that maps the image filename to an array of 4 `(x, y)` coordinates describing the associated bounding box
* If `shuffle = False`, then `self.idxs` will go in the order images were loaded. Otherwise it gets shuffled each time the loader has gone through the entire dataset
* By popping from `self.idxs` instead of `self.imgs`, the `__call__` method can loop over the set of images indefinitely  
* My pipeline uses a custom `BbResize` operator (see code below) to resize all images to 540x960 pixels and scale the bounding boxes appropriately

```
#include "bb_resize.h"
#include "dali/pipeline/operators/operator.h"
#include "dali/pipeline/data/types.h"

namespace dali {

    template<>
    void BbResize<CPUBackend>::RunImpl(SampleWorkspace *ws, const int idx) {

        // Get positional input/output(s) from workspace
        const Tensor<CPUBackend> &image = ws->Input<CPUBackend>(0);
        Dims shape = image.shape();
        int height = shape[0];
        int width = shape[1];
        const Tensor<CPUBackend> &corners = ws->Input<CPUBackend>(1); 
        Tensor<CPUBackend> &resized = ws->Output<CPUBackend>(1);

        // Copy bounding box to output
        resized.set_type(corners.type());
        resized.ResizeLike(corners);
        TypeInfo type = corners.type();
        type.Copy<CPUBackend, CPUBackend>(
            resized.raw_mutable_data(),
            corners.raw_data(), corners.size(), 0);
        double *resized_data = resized.mutable_data<double>();

        // Resize bounding box coordinates
        float resize_x = spec_.GetArgument<float>("resize_x", ws, ws->data_idx());
        float resize_y = spec_.GetArgument<float>("resize_y", ws, ws->data_idx());
        int pairs = resized.size() / 2;
        for (int i=0; i < pairs; ++i) {
            resized_data[2*i] = resized_data[2*i] * resize_x / width;
            resized_data[2*i + 1] = resized_data[2*i + 1] * resize_y / height;
        }

        // Instantiate and run Dali's ResizeCropMirror operator
        std::unique_ptr<OperatorBase> resize_ptr = InstantiateOperator(
            OpSpec("Resize")
                .AddArgumentInput("resize_x", "resize_x")
                .AddArgumentInput("resize_y", "resize_y")
                .AddArg("num_threads", spec_.GetArgument<int>("num_threads"))
                .AddArg("batch_size", spec_.GetArgument<int>("batch_size")));
        resize_ptr->Run(ws);
    }

    DALI_REGISTER_OPERATOR(BbResize, BbResize<CPUBackend>, CPU);

    DALI_SCHEMA(BbResize)
        .DocStr("Resize bounding boxes along with image")
        .NumInput(2)
        .NumOutput(2)
        .AllowMultipleInputSets()
        .AddArg("resize_x", "Pixel dimension of the rescaled image's x-dimension.",
            DALIDataType::DALI_FLOAT, true)
        .AddArg("resize_y", "Pixel dimension of the rescaled image's y-dimension.",
            DALIDataType::DALI_FLOAT, true);
}
```

Since `self.meta` is used to map the image filename to the correct corners, randomly selecting the image order should not affect the validity of the `(img, bbox)` pairs which are feed to the pipeline. However, sometimes the bounding box and plotted image do not match from visual inspection (see below)
![image](https://user-images.githubusercontent.com/39926682/55024032-a6f80580-4fc3-11e9-81f5-032394bace4a.png)
However, the majority of the time the bounding boxes line up as expected (see below). Therefore, I would expect this is not an issue with the particular operator, but something regarding my method of shuffling the images? So far, I have not been able to isolate the behavior to a particular image or order of appearance in the epoch. I only know that the operator works perfectly if images are not shuffled and periodically errors if they are shuffled. If nothing stands out to you as the culprit, I can try and upload a more complete example.
![image](https://user-images.githubusercontent.com/39926682/55024338-45846680-4fc4-11e9-9947-9ab8c0810090.png)

**Comment by awolant** [comment] 2019-03-27 08:10
Currently, only `COCOReader` supports full dataset shuffling after each epoch, so unless you have data in COCO format, there is no ready to use way of doing this.

I looked through your code and nothing stood out for me right now.

**Comment by JanuszL** [comment] 2019-03-27 16:15
@awolant - @addisonklinke is using ExternalSource and it seems that it there may be some bug there (as images and bboxes that suppose to be read together but get somehow mixed).
@addisonklinke - can you provide the piece of code how you use ShuffleLoader and ExternalSource ?
Tracked as DALI-657.

**Comment by awolant** [comment] 2019-03-27 16:24
What I meant was that example above should work, I think. I don't see anything wrong with it. I intended to wait for more complete repro of this issue, as @addisonklinke wrote at the end, and dig dipper into this.

**Comment by addisonklinke** [comment] 2019-03-27 16:27
@awolant @JanuszL Thanks for the quick response. I will work on a more complete example today (I'm on US Mountain time) so that hopefully you can take a look tomorrow

**Comment by addisonklinke** [comment] 2019-03-28 15:04
Please see the attached tarball for a complete reproducible example: [repro.tar.gz](https://github.com/NVIDIA/DALI/files/3018607/repro.tar.gz)

**Comment by addisonklinke** [comment] 2019-03-28 15:43
Please see the following [tarball](https://github.com/NVIDIA/DALI/files/3018835/repro.tar.gz) for a complete reproducible example

Note: I tried to add a `--seed` flag to control the randomness and confirmed that the `pipe._seed` attribute matches this value when it is forced. However, I cannot get predictable results for which iteration will cause the error, so you may need to run multiple times before seeing it

**Comment by awolant** [comment] 2019-03-28 17:52
Great, thanks. I will take a look at it and get back to you.

**Comment by awolant** [comment] 2019-03-29 10:20
@addisonklinke I was able to run your reproducible example. Unfortunately, I did not get single instance of this error over more than 30 full runs. Exactly how rare is it?
I was using DALI master branch build as well as couple of runs on DALI 0.7 for sanity check.
Can you tell me more about your setup for this? Or maybe can you try with more recent version of DALI?

**Comment by addisonklinke** [comment] 2019-03-29 12:20
@awolant I have been seeing between 1-5% error for Dali 0.7 with the default run size of 100 iterations. 

Here are a few more details about my setup
* Ubuntu 18.04
* Cuda 10
* Nvidia driver 417
* 1060 GPU
* Conda environment 

Are there any other details that would be helpful to know?

I will try running off the master branch on my side and see if the error persists

**Comment by awolant** [comment] 2019-03-29 14:44
@addisonklinke  ok, thanks. @ptrendx suggested that maybe this issue manifests itself only when you are running on slower hardware and I'm on TITAN, so it might be masked somehow. Let's try with never version of DALI on your part and when push comes to shove, I will try to find something more like 1060 to try this on.

**Comment by addisonklinke** [comment] 2019-03-29 14:49
@awolant I ran the `build.sh` script under `dali/docker` this morning to get the latest master branch. Once that has finished running, where do I find the wheel file it created? I didn't see any instructions in the README beyond running the shell script

**Comment by awolant** [comment] 2019-03-29 15:01
@addisonklinke if everything works fine, script should create `wheelhouse` folder with wheel inside. Please keep in mind, that this script has parameters like `CUDA_VERSION` and `PYVER` and they should match your setup.

**Comment by addisonklinke** [comment] 2019-03-29 17:25
@awolant  Although it adds complexity to the example, I can reproduce a higher frequency of errors (~90%) by running the pipeline with _all_ of its augmentations instead of just `BbResize`. This 
[tarball](https://github.com/NVIDIA/DALI/files/3023770/repro.tar.gz) has the updated example. Can you run and see if that makes a difference for you?

**Comment by awolant** [comment] 2019-03-30 16:43
@addisonklinke with the second example I started to see those errors. At a frequency of around 1-5% on TITAN, but that's enough. I suspect that we have some problem with synchronization of external inputs consumption. I was able to generate the same error without shuffling by running `python repro.py -b 8`. In the default config, batch size and dataset size were the same, so even though images and boxes where out-of-sync it did not matter, because they still matched, since they were shifted by exactly one epoch. We had similar issue in different place recently. I will continue looking into this issue next week. I will let you now, if I find something.

**Comment by addisonklinke** [comment] 2019-04-01 19:19
@awolant Thank you for looking into this more. That's very helpful to know about properly synchronizing the streams on GPU. Eventually, we want to write CUDA kernels to avoid using `cudaMemcpy`, so it's just a temporary workaround anyways

To clarify, you still saw errors even after fixing the stream synchronization? I am confused why instantiating a stock operator inside a custom one would lead to synchronization issues. Based on my [discussion](https://github.com/NVIDIA/DALI/issues/410#issuecomment-458506397) with @jantonguirao, it sounded like that is a supported feature. Mainly, I wanted to avoid copy-pasting the source code for stock operators that way my custom operators update automatically as new versions of Dali come out

**Comment by awolant** [comment] 2019-04-02 07:17
@awolant Yes, I'm still seeing the issues after fixing memory synchronization on  second example.
About operator instantiation, you are right. It should work as you used it. I was only pointing out, that maybe splitting `bb_resize` into two operators, one custom for boxes and one stock for images would solve the issue instantly, while we investigate synchronization problems. This way you do not have to copy any code from stock `Resize`. You just call it directly. What I had in mind is something like [this](https://github.com/NVIDIA/DALI/files/3032691/bb_resize.zip)
It's your original example, but with split operators for images and boxes. Passing `images` to `BbResize` is only to get their shapes.
Can you maybe test it in your setup and see, if we still have issues with it?

**Comment by addisonklinke** [comment] 2019-04-02 14:18
@awolant I made the stream synchronization changes you suggested and am now able to run the example without errors. I did 10 runs with/without shuffling and batch sizes of 5, 8, and 10, and all of these kept the bounding boxes in sync. Can you try the updated [example](https://github.com/NVIDIA/DALI/files/3034345/repro.tar.gz) on your system and let me know if operator instantiation is still causing errors?

**Comment by awolant** [comment] 2019-04-02 15:57
@addisonklinke I've tried your updated example. I still see those errors and broken images both for master branch and DALI 0.7.
Have you tried the version with separate operators that I provided?

**Comment by addisonklinke** [comment] 2019-04-02 16:09
@awolant I just ran the version with separate operators and do not see any errors regardless of shuffling

**Comment by awolant** [comment] 2019-04-02 17:34
@addisonklinke Ok, since it seems to work stably for you, let's close it for now. If the problem reappears, we can try to look into this again. 
We would strongly advise to move towards pipeline design closer to the split example I provided, as is should be more resilient to errors in the future and we could provide better support.

**Closed by awolant** 2019-04-02 17:34 UTC
Labels: bug
