### ISSUE TITLE
Batch missing when working in external Source parallel = true 

### ISSUE THREAD

**Issue by xhtsansiro** [NVIDIA/DALI#3191] opened 2021-07-28 14:31 UTC
I want the images of each batches are processed together in order to reduce the effect of long image loading. I set the "parallel = true" and let the external source work in sample mode.   Following is my code snippet: 
"pipe = Pipeline(batch_size, num_threads, device_id, py_num_workers = 32)`
 states, actions = fn.external_source(source=external_data, num_outputs=2 ,batch = False, parallel= True, prefetch_queue_depth = 32)" 
I want 32 workers working together to load images and always have enough data to feed into training. with 32 workers working together, the loading of each batch (512 images) reduce to about 0.2s. which is around 3s if i use batch mode in external Source. However, in my case, i have totally 120 batches of data.   only the first epoch iterate over 120 batches, the following epochs just iterate over around 90 batches. I don't know where the problem is.  Can you pls help?   Besides is there any way that I have more workers working on the externalSource even it is in batch mode ?   I want to minimize the effect of reading .png files (bottleneck) during training by DALI.

**Comment by JanuszL** [comment] 2021-07-28 17:09
Hi @xhtsansiro,

It is not expected and it is hard to tell what went wrong.
What you can do is to return a sample index (that the `external_data` receives as an argument) and see if there are any missing samples in the second iteration.
If it still doesn't work please provide a minimal, and self-contained reproduction we can run on our side to analyze the problem.

**Comment by xhtsansiro** [comment] 2021-07-29 07:25
Hello, @JanuszL  
thanks for your reply. I don't know what you mean by sample index, i suppose, the external source always call next function to get new sample instead of give a index and return a sample like _getitem_ in Pytorch does.
My data is not so clean and easy to handle, it consists of many sequences of images. each sequence contains around 150 images. and My neural work is a RNN,
Following are some code:
class ExternalInputIterator(object):
    def __init__(self, dir_name, batch_size = 32, timestep = 16):
             # get all the paths of the images and save in the list,      self.img_all_sequences, [sequence1, sequence2, ...., sequence N], sequence_i is a list [img_path1, img_path2, .... , img_pathN]
            # get and save all the actions, 
           # self.ls = list(range(0, len(self)))   is the list contains all the possible starting index of the image, (one batch sample contains 16 sequential images)
          # self.cumulative_size, a list has [element1, element2, element3,...,  ]. how many images can be taken as the first image of one batch sample cumulatively.  e.g. in sequence1, there are totally 115 images, but i can just take 100 batch samples, the last sample is [100, 101,...115]. In this case, element1 will be 100.  

    def __len__(self):     # how many indexes are possible for taking the first images of one batch_sample
        return self.n_data - (self.timestep-1) * len(self.cumulative_size)

    def sequence_find(self, idx):    # find which sequence to take images

        assert idx < len(self), "the index is wrong"   # because the idx in the list = length - 1
        if idx < len(self):  
            dataset_idx = bisect.bisect_right(self.cumulative_size, idx)
            if dataset_idx == 0:
                sample_idx = idx
            else:
                sample_idx = idx - self.cumulative_size[dataset_idx - 1]
        return dataset_idx, sample_idx  # sequence no.   image no.

    def __iter__(self):
        self.i = 0
        self.counter = 0
        shuffle(self.ls)        # shuffle all the starting_index.
        return self

    def __next__(self):   # get the images and actions of 

         images,actions = None, None
  
        if self.i >= len(self):
            print("already takes {} samples".format(self.i))
            self.__iter__()
            raise StopIteration

        if self.counter == 0:    # only needs to find sequence after every sequence(taking 16 images).
             startIndex  = self.ls[self.i]   # the index of the start images, list[index]
             self.sequenceIndex, self.imgIndex = self.sequence_find(startIndex)   # where to take the images

        img_path = self.img_all_sequence[self.sequenceIndex][self.imgIndex + self.counter]  # path of each img
        f = open(img_path, 'rb')
        images = np.frombuffer(f.read(), dtype=self.dtype) 
        actions = torch.tensor(self.action_all_sequence[self.sequenceIndex][self.imgIndex+self.counter,:], dtype = torch.float)
     
        self.counter += 1   # take the next images of this sequence
 
        if self.counter == self.timestep:   # after taking 16 images sequentially , needs another starting index, 
            self.i = self.i + 1
            self.counter = 0 
        return (images, actions)

    next = __next__

def ExternalSourcePipeline(batch_size, num_threads, device_id, external_data):

    pipe = Pipeline(batch_size, num_threads, device_id, py_num_workers = 32)   
    with pipe:
      #  time1 = time.time()
        states, actions = fn.external_source(source=external_data, num_outputs=2 ,batch = False, parallel= True, prefetch_queue_depth = 32)
        # parallel can only work in sample modus.
        # do the corresponding image transformation
        input = fn.decoders.image(states, device="cpu") # default output_type: RGB, support cpu, mixed
        input = fn.crop(input.gpu(), crop=[160, 384], crop_pos_x=0.5, crop_pos_y=0.833, device="gpu") # support gpu, cpu       
        input = fn.resize(input, resize_x=256., resize_y=128., device="gpu") # support gpu, cpu   
        pipe.set_outputs(input, actions)


    return pipe

dataset_train = ExternalInputIterator(DATA_NAME_TRAIN, batch_size= 32, timestep= 16 )
dataset_valid = ExternalInputIterator(DATA_NAME_VALID, batch_size= 32, timestep= 16 )

# set the pipeline for train and valid
pipe_train = ExternalSourcePipeline(batch_size=32*16, num_threads=16, device_id= 0, external_data= dataset_train)
pipe_valid = ExternalSourcePipeline(batch_size= 32*16 , num_threads=16, device_id= 0, external_data= dataset_valid)

# start the python workers
pipe_train.start_py_workers()
pipe_valid.start_py_workers()

# generator dataloader

train_loader = PytorchIterator(pipe_train, output_map =["states", "actions"], last_batch_policy = LastBatchPolicy.PARTIAL, last_batch_padded =True)
valid_loader = PytorchIterator(pipe_valid, output_map =["states", "actions"], last_batch_policy = LastBatchPolicy.PARTIAL, last_batch_padded =True)

this is the basic logic of my code, what i don't find online and don't quite understand is how those py_workers cooperate. especially at the end of the epoch. Do i need to set a mutex for self.i as it is critical variable (shared among py_workers?) to control when to stop the iteration (end the current epoch)?  

I did not put all the __init__ of externalSource here.  Since the files are not very in order,  there are many codes which are used to find corresponding file, extract value in __init__.  I do not want make it confusing.

**Comment by klecki** [comment] 2021-07-29 16:06
Hi @xhtsansiro,
I'm working on adding a tutorial that describes how to use External Source in parallel mode.
It's the PR: #3199. Before it's merged, you can access the jupyter notebooks directly by: 
https://github.com/klecki/DALI/blob/parallel-es-tutorial/docs/examples/general/data_loading/parallel_external_source.ipynb
https://github.com/klecki/DALI/blob/parallel-es-tutorial/docs/examples/general/data_loading/parallel_external_source_fork.ipynb

It should give you examples how to convert iterator to a callable object, that is compatible with Parallel External Source. The fact that the iterable worked with it is rather a bug and not a feature.

It also describes how to start workers with both 'fork' and 'spawn'. Hope this will help.

**Comment by xhtsansiro** [comment] 2021-07-29 20:04
Hi, @klecki 
thanks a lot, I will read carefully, :) 👍

**Comment by xhtsansiro** [comment] 2021-07-30 08:17
Hi @klecki 

After reading the tutorial , I understand if i want to use parallel mode, I need to use callable object to replace iterable object. 

In the __call__ function, there is an argument: sample_info. Is this sample_info the index corresponding to a specific image? Because I am thinking in my case, how I manage that, several sequence of pics are taken as a batch?

I don't see that sample_info.idx += 1 like in the iterable object. so how does it actually work when coming to the epoch end to raise the StopIteration()? And in iterable object, when an epoch ends, there will be a reset of the index, which I don't see in callable object, just want to know where and how the similar things in callable object are executed. 

Thanks in advance!

**Comment by klecki** [comment] 2021-07-30 08:54
Hi,
with a callable, every time DALI calls your function/object it will pass the [SampleInfo](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/data_types.html#sampleinfo). DALI will keep track of indices for you, and you should be able to return a sample that is requested. If DALI requests a sample with `idx_in_epoch` that is bigger than your dataset, you can raise StopIteration in the callback to indicate that your data finished, and you can call `.reset()` on the pipeline to reset the indices that DALI tracks. I will add this explanation to the tutorials.

**Comment by xhtsansiro** [comment] 2021-07-30 12:41
@klecki   thanks for the explanation. maybe one more question:
  how can I enable the shuffle of the pics after every epoch. In Pytorch, I can set shuffle = true in dataloader. However, I do not find this argument in class nvidia.dali.plugin.pytorch.DALIGenericIterator.

**Comment by JanuszL** [comment] 2021-07-30 13:25
Hi @xhtsansiro,

>how can I enable the shuffle of the pics after every epoch. In Pytorch, I can set shuffle = true in dataloader. However, I do not find this argument in class nvidia.dali.plugin.pytorch.DALIGenericIterator.

You need to do shuffling on your own inside the callback passed to the external source operator. One way would be to pass the same seed to each callback instance and use it for shuffling so you know that all callback instances have the state in sync.

**Comment by xhtsansiro** [comment] 2021-07-30 14:33
@JanuszL  Hello, Could you demonstrate an example ? one or two lines of codes will make me truly understand what you mean?  thanks

**Comment by JanuszL** [comment] 2021-07-30 15:28
Hi @xhtsansiro,

Something like this should do:
```
import random

class ExternalInputCallable:
    def __init__(self, batch_size, seed):
        random.seed(seed)
        self.images_dir = "../../data/images/"
        self.batch_size = batch_size
        with open(self.images_dir + "file_list.txt", 'r') as f:
            file_label = [line.rstrip().split(' ') for line in f if line is not '']
            self.files, self.labels = zip(*file_label)
        self.n = len(self.files)
        shuffle_seed=random.random()
        random.shuffle(self.files, shuffle_seed)
        random.shuffle(self.labels, shuffle_seed)

    def __call__(self, sample_info):
        if sample_info.idx_in_epoch >= self.n:
            shuffle_seed=random.random()
            random.shuffle(self.files, shuffle_seed)
            random.shuffle(self.labels, shuffle_seed)
            raise StopIteration()
        jpeg_filename = self.files[sample_info.idx_in_epoch]
        label = np.int32([self.labels[sample_info.idx_in_epoch]])
        with open(self.images_dir + jpeg_filename, 'rb') as f:
            encoded_img = np.frombuffer(f.read(), dtype=np.uint8)
        return encoded_img, label
```

**Comment by klecki** [comment] 2021-08-02 15:56
By the way, I expanded the tutorials a bit and fixed some minor issues. They are still not fully reviewed and merged but now there are few more details, also about epochs.

**Comment by xhtsansiro** [comment] 2021-08-02 21:21
Hello, thanks for the help.

I am now facing another problem. All the cases you demonstrated are applicable for CNN. I am now taking batches for RNN, which means each sample in one batch(say batch_size: 32) is not only one image, but (time_sequence=16) 16 sequential images. I tried with externalSource in batch mode using the iterable object. It actually works with only one python worker. I can take 512 (32 *16) pics as a batch, and do the transformation in pipeline, reshape it to (32,16,3, height, width) ,feed to the neural network. 
when it comes to the sample mode (callable), with more python workers. my first idea was to return a sample (16 sequential images in a list of array) in the callable. and do the image processing in the Pipeline. Since it is in a sample mode, I thought i can use a for_loop to iterate the Datanode of 16 sequential images, but it outputs error that Datanode cannot be iterable. 

I am wondering if i can move all the image processing steps from pipeline to the callable. (like in Pytorch, all the transformation steps are performed in _getitem_).  I don't know if DALI has some good features to handle the input of RNN. Do you have any suggestion.

**Comment by JanuszL** [comment] 2021-08-03 07:20
Hi @xhtsansiro,

> r. I can take 512 (32 *16) pics as a batch, and do the transformation in pipeline, reshape it to (32,16,3, height, width) ,feed to the neural network.
when it comes to the sample mode (callable), with more python workers. my first idea was to return a sample (16 sequential images in a list of array) in the callable. and do the image processing in the Pipeline

I think you can still return 512 samples, but in this case, every callable needs to return one image.

> Since it is in a sample mode, I thought i can use a for_loop to iterate the Datanode of 16 sequential images, but it outputs error that Datanode cannot be iterable.

Datanode is a symbolic representation - you cannot do any processing directly on it. You can only call DALI operators (including math one).

> I am wondering if i can move all the image processing steps from pipeline to the callable. (like in Pytorch, all the transformation steps are performed in getitem). 

You can but you won't utilize GPU this way and the performance could be suboptimal, still, it is feasible.

**Comment by xhtsansiro** [comment] 2021-08-09 09:29
Hi @JanuszL 

if I have 16 pyworkers,  how do these workers cooperate when invoking the callable? 
each worker is responsible for the data_fetch of one batch individually ? if batch_size = 32,  then 
the first worker has starting_idx = 0,  it will fetch all data from idx=0 to idx= 31.  the second worker has starting_idx = 32, will fetch all the data from idx=32 to idx =63. ...., 
that' s what i derive from the output of following snippet, right?  Or  each worker fetches one image of one batch sample, and together they finish the fetch of one batch. 

I have to do quite lots modification on the external source object in order to fit the dataset. therefore it will be very useful to know exactly how the workers processing data. 

` def __call__(self, sample_info):

        if sample_info.iteration >= self.iterations:
            random.shuffle(self.ls, self.seed)
            raise StopIteration()

        print("current idx in the epoch is {}".format (sample_info.idx_in_epoch))
`

<img width="608" alt="WeChat9af1e693c5da9ca70cb2b27ba0667bb6" src="https://user-images.githubusercontent.com/55890308/128685074-a78d6260-09e8-41dd-8a5f-8295d9fe1f67.png">


Thanks!

**Comment by klecki** [comment] 2021-08-09 10:55
Hi @xhtsansiro,
all workers contribute to computing one batch at the time, so if you have batch_size=32 and 16 workers, this means that each of them will be asked to return 2 samples.

I tried to reproduce what your output shows, printing the iteration as well:
```
print("current idx in the epoch is {}, iter {}".format (sample_info.idx_in_epoch, sample_info.iteration))
```
and I think it comes from the `prefetch_queue_depth` which you specified to 32. This is a bit high, and it means that the external source will prepare ahead of time 32 batches of data - you can tune this parameter, but I don't think going above 2 or 3 should be necessary, unless you have a really high sample processing time variance and see actual slowdown. I may even suggest that you should start with just using the default.

From what my experiments show your output probably shows the workers executing the callback for the consecutive iterations (the big `prefetch_queue_depth`), hence the "jumps" in the sample index that you see.

**Comment by xhtsansiro** [comment] 2021-08-09 13:55
Hi, @klecki 

I think you are right, I set a very high prefetch_queue_depth, I then use the default and check what is printed out, 
it matches what you said, each worker is responsible for 2 samples?  right? the first worker takes sample 0, sample 1, the second worker takes sample 2, sample3,  and so on...  . each worker will call the callable 2 times. 

<img width="1138" alt="WeChat4252c49db239db829e9ad43a5760a7fa" src="https://user-images.githubusercontent.com/55890308/128708910-533a6045-a292-4212-adf1-33c220d14eff.png">

**Comment by klecki** [comment] 2021-08-09 14:01
Yes, the current implementation splits the work the way you described (if the batch is divisible by the number of workers). I just want to remind, that the workers are in separate processes and cannot communicate with each other.

**Comment by JanuszL** [comment] 2021-08-09 14:15
And the work splitting strategy is an implementation detail so it can change and you should not rely on its particular behavior.

**Comment by xhtsansiro** [comment] 2021-08-09 14:33
Hi, I want to see how many times the callable are invoked by all the workers (in my case 16 workers). 
as following shows:

`self.lock  = multiprocessing.Lock()
 self.cc_c = multiprocessing.Value("i", 0)

 def __call__(self, sample_info):

        self.lock.acquire()
        self.cc_c.value += 1
        print("how many times the callable is invoked {}".format(self.cc_c.value))
        self.lock.release()
`
I thought the value of self.cc_c will increase 1 after every callable. the output should always be in sequence like 1,2,3,4...,. However what i get is not what i expect. I wonder if this way is compatible with DALI.

<img width="970" alt="WeChatb8cfd73a7ac1119f16a9aa6d7d6eddb0" src="https://user-images.githubusercontent.com/55890308/128723692-7e5e2a58-f942-4ca1-8534-d87af16c637e.png">

**Comment by klecki** [comment] 2021-08-09 16:20
In what scope do you crate that `multiprocessing.Lock` and `multiprocessing.Value`? It looks a bit like the processes got a copy of those, instead of the common one. Depending on the start method the resources can be shared or not, so this might also play a role here.

We didn't test how the communication via shared memory from multiprocessing works as we have our own, internal shared memory wrappers to support earlier Python versions.

**Comment by xhtsansiro** [comment] 2021-08-09 16:57
I created 'multiprocessing.Lock' and 'multiprocessing.Value' in the __init__ of the ExternalSource Class.  
If I want to know how many times the callable is called by all the workers, how can i realize that by using your internal shared memory wrapper?  Thanks!

**Comment by klecki** [comment] 2021-08-09 17:11
In principle, the callback is called `batch_size` times for every iteration that DALI runs. DALI by default has a queue of 2 iterations prepared ahead. 

The parallel mode is intended to work by requesting samples by sample info, as the worker processes have independent copies of the callback in separate processes. 

Do you need to have some communication between them? I'm not sure how feasible it is, but if we know more about what you want to achieve we may be able to scope and implement such feature.

@stiepan may be able to say a bit more about what is going on with the `multiprocessing.Value`.

> how can i realize that by using your internal shared memory wrapper

I just wanted to mention that we didn't test native Python shared memory wrappers, as we use our own for the communication, but this is an internal part of the DALI implementation and it's not possible to use it for user-defined communication with the workers.

**Comment by xhtsansiro** [comment] 2021-08-09 18:22
Hi, @klecki  

thanks for the detailed explanation. 
My dataset consists of 100 small datasets. Each dataset has 100 sequential pictures (pic1, pic2,.... pic100), which are taken in order.  No time connection between datasets.
My neural network is a RNN based one. each batch (batch_size=32) sample is 16 sequential pictures. I got all the paths of images saved in a list of list [dataset1, dataset2, .... dataset100]  , each dataset is a list of [path1, path2, ... path100]. 
For each dataset, I can have 85 samples, [pic1, ... pic16],..., [pic85, ... pic 100]. 
Now,  I got a list to store the cumulative size of how many samples i can take in every dataset. It should be something like [85, 170, 255,...., 8500].  I get a idx from 0 to 8499,. based on this idx,  i can decide from which dataset (calculate out a dataset_idx) I fetch pic, and which pic in the dataset I will take as the starting pic of the 16 pics. Then I fetch 16 images in this dataset as one batch sample. Then I get a new idx, from which i figure out from which dataset i should take the batch sample, (repeat the steps).
That's why i want a variable, say counter = 0,  in the __call__ to counter how many times the workers have called the callable. 
  something like following:
' 
self. counter = 0
self. ls = list(range(8499))
shuffle(self.ls)
def __call__(self, sample_info):

      if self.counter %16 ==0:    
           self. counter =0 
           self.idx =  self.ls[sample_info.idx_in_epoch]

           self.dataset_idx, self.img_idx = function (self.idx,...)

img = open(path[self.dataset_idx][self.img_idx + self.counter])
action = np.array (action[self.dataset_idx][self.img_idx + self.counter] )
self.counter += 1. 

'
with self.counter, I take a new idx after each 16 pictures, which are taken in sequence from one dataset as a batch sample and then take another batch sample, till i take 32 batch samples for one batch.  hence it is important that the variable self.counter are increased by every worker in order. 

That is what i want to achieve.  hope you can give me some suggestion.  :)

**Comment by JanuszL** [comment] 2021-08-09 22:08
Hi @xhtsansiro,

I think that is what the `sample_info.idx_in_epoch` is for. In your case, each call should get a unique value between 0 to 8499. If it is bigger you should raise a `StopIteration` exception to let the external source know that it runs out of data.

>  I take a new idx after each 16 pictures, which are taken in sequence from one dataset as a batch sample and then take another batch sample, till i take 32 batch samples for one batch. hence it is important that the variable self.counter are increased by every worker in order.

I think something like this should work (the `sample_info.idx_in_epoch` value should be sufficient, you don't have to maintain a global `self.counter` state):
```
def call(self, sample_info):
  if sample_info.idx_in_epoch > 8499:
    raise StopIteration
  dataset_idx, img_idx_start = function (sample_info.idx_in_epoch,...)
  imgs = [ ]
  action = []
  for img_idx in range(img_idx_start, img_idx_start+ 16):
     imgs.append(open(path[self.dataset_idx][img_idx]))
     action.append(np.array (action[dataset_idx][img_idx] ))
```

**Comment by xhtsansiro** [comment] 2021-08-10 07:02
Hi, @JanuszL 
`for img_idx in range(img_idx_start, img_idx_start+ 16):
     imgs.append(open(path[self.dataset_idx][img_idx]))
     action.append(np.array (action[dataset_idx][img_idx] ))`

i have tried something like this. But there is a problem. in the call, I get a list of 16 images, a list of actions. Then I want the pipe to work in sample mode, (batch mode does not support multi workers, and parallel). it will output the error that shows the states cannot match the existed format, because sample mode expect an image from the external source instead of a list of images.   By the way, does the batch mode support parallel working (multi processing)? I find it does not in your documentation, just wonder if this feature will be added later?  
Thanks!
`

def ExternalSourcePipeline(batch_size, num_threads, device_id, external_data):
   
    pipe = Pipeline(batch_size, num_threads, device_id, py_num_workers = 16, py_start_method = "fork") 
    with pipe:
        states, actions = fn.external_source(source=external_data, num_outputs=2 ,batch = False, parallel= True)            
  
        # parallel can only work in sample modus.

        # do the corresponding image transformation， states = list of array [pic1, pic2, ..., pic16]
        # for img in states: DataNode cannot be iterable
        input = fn.decoders.image(states, device="cpu") # default output_type: RGB, support cpu, mixed
        input = fn.crop(input.gpu(), crop=[160, 384], crop_pos_x=0.5, crop_pos_y=0.833, device="gpu") # support gpu, cpu
        print(input.device) ## where is this input
        input = fn.resize(input, resize_x=256., resize_y=128., device="gpu") # support gpu, cpu
        print(input.device) ## where is this input
        
      #  output = fn.cast(images, dtype=types.UINT8)
        pipe.set_outputs(input, actions)
       # print("the image processing takes {}".format(time.time()-time1))

    return pipe

`

**Comment by stiepan** [comment] 2021-08-10 08:38
Hi @xhtsansiro

Could you provide more details regarding your example with multiprocessing.Value? What method of starting the pool (py_start_method) did you use, what was the prefetch_queue_depth and what Python version did you run? Even tough ExternalSource was not intended for use with multiprocessing shared state, it is rather surprising behavior. I'd like to investigate it further, but wasn't able to reproduce your output.

**Comment by JanuszL** [comment] 2021-08-10 09:28
@xhtsansiro,

Yes, you are right, I didn't fully understand what you want to do. How about such code:
```
import numpy as np
import nvidia.dali.fn as fn
from nvidia.dali import pipeline_def
import os

batch_size = 10
sequence_lenght = 4

test_data_root = os.environ['DALI_EXTRA_PATH']
jpeg_file = os.path.join(test_data_root, 'db', 'single', 'jpeg', '510', 'ship-1083562_640.jpg')

def get_data(sample_info):
    out = [np.fromfile(jpeg_file, dtype=np.uint8) for _ in range(sequence_lenght)]
    return out

@pipeline_def
def simple_pipeline():
    jpegs = fn.external_source(source=get_data, num_outputs=sequence_lenght, parallel=True, batch=False)
    images = fn.decoders.image(jpegs)
    sequence = fn.stack(*images)
    sequence = fn.reshape(sequence, layout="DHWC")
    return sequence

pipe = simple_pipeline(batch_size=batch_size, num_threads=4, prefetch_queue_depth=2, device_id=0)
pipe.build()
pipe.run()
out = pipe.run()[0]
print(np.array(out[0]).shape)
```
It should yield a sequence as you want. Keep in mind that `fn.decoders.image` would be created for each image in the sequence and for the `mixed` backend it would consume a lot of GPU memory (As each instance would allocate a separate GPU buffer).

**Comment by xhtsansiro** [comment] 2021-08-11 08:17
Hi, @stiepan 
my example is like following 
'
def __init__():
       self.lock. = multiprocessing.Lock()
       self.counter = multiprocessing.Value('i', 0)

def __call__ ():
        self.lock.acquire()
        self.counter.value += 1
        print("how many times the callable is invoked {}".format(self.counter.value))
        self.lock.release()

After defining the pipe, I use pipe.start_py_workers(). I do not give prefetch_queue_depth a value in fn.external_source, which means, it is default value. The python version I am using is python 3.8.

**Comment by xhtsansiro** [comment] 2021-08-11 08:42
Hi， @JanuszL 

Thanks a lot. the code snippet you provided helps me a lot, means I can return sequential images in callable and by setting the num_outputs = sequence_length in the pipeline, then the image processing can be done without any error. In my Code, I just set the num_outputs = 2. 

what about if I also want to yield the labels of the images (a np array for each image). something following works?

def get_data(sample_info):
    out = [np.fromfile(jpeg_file, dtype=np.uint8) for _ in range(sequence_lenght)]
    labels =[np.array()  for _ in range(sequence_length)]
    labels = torch. tensor(labels) # change the array list to tensor
    return out, labels

@pipeline_def
def simple_pipeline():
    jpegs, labels = fn.external_source(source=get_data, num_outputs=sequence_lenght + 1, parallel=True, batch=False)
    images = fn.decoders.image(jpegs)
    sequence = fn.stack(*images)
    sequence = fn.reshape(sequence, layout="DHWC")
    return sequence , labels

the variable jpeg gets the first 16 input from the external source, which are 16 images. and the variable labels gets one tensor input from the external source. 

Thanks

**Comment by JanuszL** [comment] 2021-08-11 11:02
Hi @xhtsansiro,
If you want to return the label as well you can do something like this:
```
import numpy as np
import nvidia.dali.fn as fn
from nvidia.dali import pipeline_def
import os

batch_size = 10
sequence_length = 4

test_data_root = os.environ['DALI_EXTRA_PATH']
jpeg_file = os.path.join(test_data_root, 'db', 'single', 'jpeg', '510', 'ship-1083562_640.jpg')

def get_data(sample_info):
    out = [np.fromfile(jpeg_file, dtype=np.uint8) for _ in range(sequence_length)]
    # add lable
    out.append(np.array([1,2,3]))
    return out

@pipeline_def
def simple_pipeline():
    *jpegs, label = fn.external_source(source=get_data, num_outputs=sequence_length+1, parallel=True, batch=False)
    images = fn.decoders.image(jpegs)
    sequence = fn.stack(*images)
    sequence = fn.reshape(sequence, layout="DHWC")
    return sequence, label

pipe = simple_pipeline(batch_size=batch_size, num_threads=4, prefetch_queue_depth=2, device_id=0)
pipe.build()
pipe.run()
out = pipe.run()
print(np.array(out[0][0]).shape)
print(np.array(out[1][0]))
```

**Comment by xhtsansiro** [comment] 2021-08-16 07:06
thanks, I think it should work,

**Closed** 2021-08-30 18:37 UTC
Labels: question
