### ISSUE TITLE
DALIGenericIterator too slow

### ISSUE THREAD

**Issue by sinoaidi** [NVIDIA/DALI#4636] opened 2023-02-03 07:11 UTC
why DALIGenericIterator consume about six minutes?

**Comment by JanuszL** [comment] 2023-02-03 08:14
Hi @sinoaidi,

Thank you for reaching out. Could you tell us more about your use case and/or provide [minimal, complete, and verifiable reproduction steps](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions)? Without that, we cannot tell where the problem is.

**Comment by JanuszL** [comment] 2024-01-24 15:00
Closing as stalled.

**Closed** 2024-01-24 14:59 UTC
Labels: help wanted
