### ISSUE TITLE
how to do a image zoom?

### ISSUE THREAD

**Issue by wangdada-love** [NVIDIA/DALI#5295] opened 2024-01-30 05:39 UTC
### Describe the question.

I want to use method fn.warp_affine() combined with method fn.transform.crop() to perform random zoom_crop transformation on the image. The code is as follows:
```python
def rand_zoom(images, labels, dtype=types.DALIDataType.INT32, x_zoom_range=[0.8, 1.2], y_zoom_range=[0.5, 1.5], size=[512, 512], device="gpu"):
    x_zoom = dali_rand([x_zoom_range[0]-1, x_zoom_range[1]-1])  # dali_rand() is a function that generates random numbers by encapsulating fn.random.uniform()
    y_zoom = dali_rand([y_zoom_range[0]-1, y_zoom_range[1]-1])

    from_start_x_factor = x_zoom
    from_end_x_factor = 1 - x_zoom
    from_start_y_factor = y_zoom
    from_end_y_factor = 1 - y_zoom

    affine_matix = fn.transforms.crop(from_start=[512. * from_start_x_factor, 512. * from_start_y_factor], from_end=[512., 512.], to_start=[.0,.0], to_end=[512., 512.])
    images = fn.warp_affine(images, matrix=affine_matix, fill_value=0, size=size, device=device)
    # images = fn.cast(images, dtype=dali.types.DALIDataType.UINT8)
    return images, labels
```

But I received the following error message:
```text
TypeError: float() argument must be a string or a number, not 'DataNode'
```
It means that DataNode data cannot be directly computed with float type data. 
So I write the constants inside the function as dali. types. Constant objects and use these objects for calculations. the code as below:
```python
def rand_zoom(images, labels, dtype=types.DALIDataType.INT32, x_zoom_range=[0.8, 1.2], y_zoom_range=[0.5, 1.5], size=[512, 512], device="gpu"):
    x_zoom = dali_rand([x_zoom_range[0]-1, x_zoom_range[1]-1]) # range=x_zoom_range
    y_zoom = dali_rand([y_zoom_range[0]-1, y_zoom_range[1]-1]) # range=y_zoom_range

    base = dali.types.Constant(1.0) # , dtype=dali.types.DALIDataType.FLOAT
    height = dali.types.Constant(size[0], dtype=dali.types.DALIDataType.FLOAT)
    width = dali.types.Constant(size[1], dtype=dali.types.DALIDataType.FLOAT)
    origin = dali.types.Constant(0.0, dtype=dali.types.DALIDataType.FLOAT)

    from_start_x_factor = x_zoom
    from_end_x_factor = base - x_zoom
    from_start_y_factor = y_zoom
    from_end_y_factor = base - y_zoom

    affine_matix = fn.transforms.crop(from_start=[width * from_start_x_factor, height * from_start_y_factor], from_end=[width, height], to_start=[origin,origin], to_end=[width, height])
    images = fn.warp_affine(images, matrix=affine_matix, fill_value=0, size=size, device=device)
    labels = fn.warp_affine(labels, matrix=affine_matix, fill_value=0, size=size, device=device)
    images = fn.cast(images, dtype=dali.types.DALIDataType.UINT8)
    return images, labels
```
But I still received the following error:
```text
TypeError: float() argument must be a string or a number, not 'DataNode'
```
I don't know why, please tell me how to achieve random image zoom_crop??

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment] 2024-01-30 08:31
Hi @wangdada-love,

Thank you for reaching out.
Can you provide a self-contained code that we can run on our end, even using toy data from https://github.com/NVIDIA/DALI_extra.
Also, I don't think you can:
```
from_start=[width * from_start_x_factor, height * from_start_y_factor]
```
as the documentation states:
```
from_start (float or list of float or TensorList of float, optional, default = [0.0])
```
while you provide a list of TensorList. You should use `cat`/`stack` operator to merge two TensorLists together and provide it as one value.

**Comment by wangdada-love** [comment] 2024-01-30 08:37
the dali_rand() function as below:
```python
def dali_rand(range, device="cpu"):
    low = range[0]
    high = range[1]
    return dali.fn.random.uniform(range=[0.0, 1.0], device=device) * (high - low) + low
```

How to implement the correct method of random zoom and crop?

**Comment by wangdada-love** [comment] 2024-01-30 08:41
I think the main problem is the arithmetic operations between float  and DataNode is not supported.

**Comment by wangdada-love** [comment] 2024-01-30 09:01
## the `main.py`:
```python
import os
import cupy
import nvidia.dali as dali
from nvidia.dali import pipeline_def, Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.tfrecord as tfrec
import nvidia.dali.types as types
import nvidia.dali.plugin.tf as dali_tf

from data_augs import rand_zoom

def test_pipeline(pipe:Pipeline, save_path='./check_data_out'):

    os.makedirs(save_path, exist_ok=True)
    print(f"checking the pipeline, result save in {save_path}")
    for ep in range(3):
        print(f'epoch {ep} ......')
        pipe.build()

        for i in range(5):

            raw_images, raw_labels, images, masks = pipe.run()
            # print(type(images))  # gpu

            images = images.as_cpu()
            # print(type(images)) # cpu
            # print('images shape: ', images.shape)
            # print(param.at(0))
            raw_images = raw_images.as_cpu()
            raw_image = raw_images.at(0)
            raw_image = Image.fromarray(raw_image)
            raw_image.save(os.path.join(save_path, f'test{i}_ep{ep}_raw.png'))

            img = images.at(0)
            # print('img shape: ', img.shape) # 512, 512, 3
            img = Image.fromarray(img)
            img.save(os.path.join(save_path, f'test{i}_ep{ep}.png'))

all_record_files = tf.io.gfile.glob("./tfrecord/*.tfrecord")
all_idx_files = tf.io.gfile.glob("./idx_files/*.idx") 

@pipeline_def(device_id=0, batch_size=BATCH_SIZE_PER_DEV, num_threads=4, enable_conditionals=True)
def semantic_segmentation_pipeline(shard_id=0, augment=True):
    inputs = fn.readers.tfrecord(
        path=all_record_files,
        index_path=all_idx_files,
        features={
            "image/encoded" : tfrec.FixedLenFeature((), tfrec.string, ""),
            "image/filename": tfrec.FixedLenFeature([], tfrec.string, ""),
            "image/format": tfrec.FixedLenFeature((), tfrec.string, "png"),
            "image/height": tfrec.VarLenFeature((), tfrec.int64, 0),
            "image/width": tfrec.VarLenFeature((), tfrec.int64, 0),
            "image/segmentation/class/encoded": tfrec.FixedLenFeature((), tfrec.string, ""),
            "image/segmentation/class/format": tfrec.FixedLenFeature((), tfrec.string,  "png")},
            random_shuffle=True, shard_id=shard_id, num_shards=NUM_DEVICES, prefetch_queue_depth=BATCH_SIZE_PER_DEV)
    images = inputs["image/encoded"]
    labels = inputs["image/segmentation/class/encoded"]
    images = fn.decoders.image(images, device="mixed", output_type=types.RGB)
    labels = fn.decoders.image(labels, device="mixed", output_type=types.GRAY)
    images = fn.resize(images, size=(512,512), minibatch_size=BATCH_SIZE_PER_DEV, device="gpu")
    labels = fn.resize(labels, size=(512,512), minibatch_size=BATCH_SIZE_PER_DEV, device="gpu")

    raw_images = images
    raw_labels = labels
    # augmentation
    if augment:
        ##  Error!!!
        images, labels = rand_zoom(images, labels, x_zoom_range=[-0.2, 0.2], y_zoom_range=[-0.2, 0.2], device="gpu")

    labels = fn.cast(labels, dtype=types.DALIDataType.INT32)
    # if fn.random.coin_flip()
    labels = fn.reshape(labels, shape=[-1, 512*512])  # must be continues
    labels = fn.one_hot(labels, num_classes=NUM_CLASSES, dtype=types.DALIDataType.INT32)
    # images = fn.crop_mirror_normalize(
    #     images,
    #     dtype=types.FLOAT,
    #     mean=[127.5, 127.5, 127.5],
    #     std=[127.5, 127.5, 127.5],
    #     output_layout="HWC")
    
    return raw_images, raw_labels, images, labels

# check pipeline......
pipe = semantic_segmentation_pipeline()
test_pipeline(pipe)
```
## the `data_aug.py`:
```python
import os
import nvidia.dali as dali
from nvidia.dali import math
import nvidia.dali.fn as fn
import nvidia.dali.tfrecord as tfrec
import nvidia.dali.types as types
import nvidia.dali.plugin.tf as dali_tf
import functools
import time
import numpy as np
import cupy
import random
import math

def dali_rand(range, device="cpu"):
    low = range[0]
    high = range[1]
    return dali.fn.random.uniform(range=[0.0, 1.0], device=device) * (high - low) + low

def rand_run(prob):
    def rand_run_decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            print(f"========{func.__name__}=======")
            # print(f"args:\n\t{args}")
            # print(f"kwargs:\n\t{kwargs}")
            if fn.random.uniform(range=[0.0, 1.0]) < prob:
                return func(*args, **kwargs)
            elif len(args) == 1:
                return args[0]
            else:
                return args
        return wrapper
    return rand_run_decorator

@rand_run(prob=1.0) # 0.2
def rand_zoom(images, labels, dtype=types.DALIDataType.INT32, x_zoom_range=[0.8, 1.2], y_zoom_range=[0.5, 1.5], size=[512, 512], device="gpu"):
    x_zoom = dali_rand(x_zoom_range) # range=x_zoom_range
    print(x_zoom)
    y_zoom = dali_rand(y_zoom_range) # range=y_zoom_range
    x_zoom = dali.types.Constant(1.0)
    print(x_zoom)
    y_zoom = 0.1
    # # 使用fn.transforms.scale的方法生成变换矩阵

    # affine_matix = fn.transforms.scale(scale=[x_zoom, y_zoom, 1])
    # # affine_matix = cupy.array((x_zoom, 0.0, 0.0, 0.0, y_zoom, 0.0))
    # # affine_matix = dali.tensors.TensorListGPU(affine_matix, device=device)
    # # affine_matix = [x_zoom, 0.0, 0.0, 0.0, y_zoom, 0.0]
    # images = fn.warp_affine(images, matrix=affine_matix, fill_value=0, size=size, device=device) #  dtype=dtype,
    # labels = fn.warp_affine(labels, affine_matix, fill_value=0, size=size, device=device) # , dtype=dtype
    # 定义用于缩放的x，y起点的坐标系数
    base = dali.types.Constant(1.0) # , dtype=dali.types.DALIDataType.FLOAT
    print(base)
    height = dali.types.Constant(size[0], dtype=dali.types.DALIDataType.FLOAT)
    width = dali.types.Constant(size[1], dtype=dali.types.DALIDataType.FLOAT)
    origin = dali.types.Constant(0.0, dtype=dali.types.DALIDataType.FLOAT)
    from_start_x_factor = x_zoom
    from_end_x_factor = base - x_zoom
    from_start_y_factor = y_zoom
    from_end_y_factor = base - y_zoom

    affine_matix = fn.transforms.crop(from_start=[width * from_start_x_factor, height * from_start_y_factor], from_end=[width*from_end_x_factor, height*from_end_y_factor], to_start=[origin,origin], to_end=[width, height])
    images = fn.warp_affine(images, matrix=affine_matix, fill_value=0, size=size, device=device)
    images = fn.cast(images, dtype=dali.types.DALIDataType.UINT8)
    return images, labels
```
Our data is confidential and cannot be uploaded. Can you generate some tfrecord data that matches the features shown in the code?

**Comment by szkarpinski** [comment] 2024-01-30 09:16
@wangdada-love Thank you for providing the full code, I'll try to reproduce your problem

**Comment by wangdada-love** [comment] 2024-01-30 09:19
At the beginning of the first script, a line needs to be added: `import tensorflow as tf`
thanks.

**Comment by wangdada-love** [comment] 2024-01-30 09:26
the requirments are:

```text
cupy==12.2.0
keras==2.13.1
matplotlib==3.8.2
numpy==1.24.3
nvidia-dali-cuda110==1.32.0
nvidia-dali-tf-plugin-cuda110==1.32.0
opencv-python==4.8.1.78
scipy==1.11.4
tensorboard==2.13.0
tensorflow==2.13.0
```

**Comment by szkarpinski** [comment] 2024-01-30 10:53
@wangdada-love The problem in your original question, which resulted in
```
TypeError: float() argument must be a string or a number, not 'DataNode'
```
was, as @JanuszL mentioned, that you were passing a list of `DataNodes` to `crop`, while the allowed types are "float or list of float or TensorList of float". 

DALI assumed that it's a list of floats or float-like elements (because that's the only allowed kind of list for this operator), so it tried to convert each element to `float`. This application of `float()` to `DataNode` resulted in the non-obvious error that you've seen.

This can be fixed by changing your list of 1D tensors into a single 2D tensor using [fn.stack](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.stack.html), like this:
```
...
from_start=fn.stack(width * from_start_x_factor, height * from_start_y_factor)
```

The problem with your changed code is that, as you noticed correctly, arithmetic operations on DALI constants are not supported (i.e. you can add a DataNode and a tensor, but you can't add two constants). We'll discuss adding such support, but for now it'd better to just stick to raw Python types.

**Comment by wangdada-love** [comment] 2024-01-31 00:45
The problem has been solved. Thank you very much for your generous teaching

**Closed** 2024-01-31 08:32 UTC
Labels: question
